### ISSUE TITLE
Debian package (Link)

### ISSUE THREAD

**Issue by markmr** [eteran/nedit-ng#101]
For those interested, here is a link to a debian package:
http://fserver.alburg.selfhost.me/NEdit-NG/Download/
(This is not a problem report. Perhaps it should be moved to a better place. Wiki?)

**Comment by eteran** [comment]
I have pinned this "issue" so that it is easier for people to find. I may make a wiki entry for it as well :-).

Thanks!

**Comment by tree-t** [comment]
> For those interested, here is a link to a debian package: http://fserver.alburg.selfhost.me/NEdit-NG/Download/ (This is not a problem report. Perhaps it should be moved to a better place. Wiki?)

Hello @markmr 👋
I am not able to open the link provided (as neither do I have an account for the website nor do I live in a German-speaking area),
So it would be nice if there could be a GitHub repository for the debian package(so it can be used in ```sources.list``` and updated there itself with every new update in *Nedit-NG* )
Regards,
Tree-J

**Comment by eteran** [comment]
I plan to improve the CI pipeline to create packages for various distros soon!

**Comment by tree-t** [comment]
Thanks for the information 🙂
Is there any way I can contribute?

Regards,
Tree-J

**Comment by eteran** [comment]
Of course!

If you happen to know how to best create a .deb and can show me an example of it, I can use that as a template for the CI pipeline

**Comment by markmr** [comment]
Hello Tree-J!
The link has pointed to a broken redirection. I have repaired it, so at least you can access the files. But these are very outdated!
Markus

**Comment by tree-t** [comment]
Hi @markmr👋
It actually just points to the exactly same 
telekom website...
Could you please tell how you were able to create the .deb package(as in the procedure)?
Regards,
Tree-J

**Comment by tree-t** [comment]
> Of course!
> 
> If you happen to know how to best create a .deb and can show me an example of it, I can use that as a template for the CI pipeline


Hello @eteran  👋

Yes, after looking here and there, I realised that it's pretty easy to do so.
All you need to do, is to run 
```
cpack -g deb
```
After running (the following is from the docs[of Nedit-NG], just to give a kind of reference point)
```
cmake ..
```
P.S: The method I used is actually just gonna create a .deb package (supposedly arch specific), but you may want to look at other options offered by cpack. And you can also create packages for a few other distros also( like RPM - for Redhat and more)
Regards,
Tree-J

**Comment by tree-t** [comment]
Here is the .deb file which was generated by cpack:
[nedit-ng_2020.1_arm64.deb](https://github.com/tree-t/Nedit-NG-Debian-Packages/blob/main/arm64/nedit-ng_2020.1_arm64.deb) 
Note: I've created a dummy repository which I can remove if you wish. (The main aim here was so that in a while I could turn this repository into a mirror for the Debian package, so that `apt update` can easily update Nedit-NG.
Regards,
Tree-J

**Comment by markmr** [comment]
> It actually just points to the exactly same
> telekom website...
The link has been repaired. I have just verified. 
May be you should clear your browser cache. 
Markus

**Comment by tree-t** [comment]
> > It actually just points to the exactly same
> > telekom website...
> The link has been repaired. I have just verified. 
> May be you should clear your browser cache. 
> Markus
> 

Hello Markus 👋
I think that this issue might be stretching too long, but this is what I'm getting now (after clearing browser cache ):
![IMG_20230604_130224.jpg](https://github.com/eteran/nedit-ng/assets/98072621/65f40ee9-ee93-4835-b315-234c859e6247)

Maybe you could upload the file here itself or a gdrive/onedrive/mega/mediafire link might also work.

Regards,
Tree-J

**Comment by markmr** [comment]
> Maybe you could upload the file here itself or a gdrive/onedrive/mega/mediafire link might also work.
This is a direct link: https://magentacloud.de/s/PF2M9JiFN98mZep
Below are zipped archives.
Markus
[2019.2-0.1.zip](https://github.com/eteran/nedit-ng/files/11710124/2019.2-0.1.zip)
[2019.2-20190522.zip](https://github.com/eteran/nedit-ng/files/11710128/2019.2-20190522.zip)
[2019.2-20190613.zip](https://github.com/eteran/nedit-ng/files/11710129/2019.2-20190613.zip)

**Comment by tree-t** [comment]
> > Maybe you could upload the file here itself or a gdrive/onedrive/mega/mediafire link might also work.
> This is a direct link: https://magentacloud.de/s/PF2M9JiFN98mZep
> Below are zipped archives.
> Markus
> [2019.2-0.1.zip](https://github.com/eteran/nedit-ng/files/11710124/2019.2-0.1.zip)
> [2019.2-20190522.zip](https://github.com/eteran/nedit-ng/files/11710128/2019.2-20190522.zip)
> [2019.2-20190613.zip](https://github.com/eteran/nedit-ng/files/11710129/2019.2-20190613.zip)
> 

Thank you @markmr ,
The direct link works fine for me ☺️
I want to thank you for bearing with me ,
And, I really like the work you did in the package creation 😉
Regards,
Tree-J
