### ISSUE TITLE
nc-ng -svrname usage

### ISSUE THREAD

**Issue by marilmanen** [eteran/nedit-ng#102]
There seems to be some issue with the -svrname option.

Here are the commands I use to get two tabs in a single NEdit with a given server name
nedit-nc -svrname test CMakeLists.txt
nedit-nc -svrname test CMakeSettings.json 

With similar commands nc-ng gives two separate Untitled windows.
nc-ng -svrname test CMakeLists.txt
nc-ng -svrname test CMakeSettings.json

**Comment by eteran** [comment]
This may be a duplicate of another issue which we thought was resolved. I'll investigate!

Thanks for the report

**Comment by eteran** [comment]
Well yea, I can reproduce this locally. I will fix this ASAP!

**Comment by eteran** [comment]
Should be fixed in latest master

**Comment by anjohnson** [comment]
This fix seems to have resolved _part_ of my issue (now #98) that I was getting extra Untitled windows.
