### ISSUE TITLE
macro examples

### ISSUE THREAD

**Issue by marilmanen** [eteran/nedit-ng#108]
Is there a place where people can share macro commands? I have many macros and some of them could be usable for others at least as an example.

**Comment by eteran** [comment]
I think we should set up a section of the Wiki!

**Comment by eteran** [comment]
Github has changed where the permissions for wiki editing are located since the last time I looked, so I'm not sure if regular users have edit rights.

Try to see if you can make a "Macro Examples" page, and let me know if you run into any issues.

**Comment by marilmanen** [comment]
I can't see any way (no push buttons or similar) in the wiki tab to create a new wiki page

**Comment by eteran** [comment]
OK, let me see if there is a way for me to grant wiki edit access then

**Comment by eteran** [comment]
The Wiki should be publically editable now.
