### ISSUE TITLE
nedit crash with read_file macro command

### ISSUE THREAD

**Issue by marilmanen** [eteran/nedit-ng#113]
NEdit-ng will crash if macro accidentally calls `read_file()` with a directory name.
Here is a simple example.

    read_file("/tmp")

**Comment by eteran** [comment]
I will get on it! Thanks!

**Comment by eteran** [comment]
Should be fixed in master now. NEdit will return an empty string and set `$readStatus` to `false` if it cannot read the file for any reason, including if it is a directory.

**Comment by marilmanen** [comment]
Partly related to this case, but maybe a more complex topic.

Here is a new (incorrectly written) macro to get a crash if the /tmp/foobar does not exist
if ( read_file("/tmp/foobar") == 1 ) {
  dialog("here")
}

There's no crash when the compare is done correctly with a string value
if ( read_file("/tmp/foobar") == "1" ) {
  dialog("here")
}

**Comment by eteran** [comment]
I assume that the original NEdit does not crash with that? nedit-ng's macro code is a port of the old code, so just trying to figure out if I introduced the bug during porting, or if this is something we've inherited.

**Comment by marilmanen** [comment]
Yes, I forgot to mention that there's no crash with the original NEdit

**Comment by eteran** [comment]
@marilmanen 

this was an unrelated issue involving the implicit conversion of integers to strings, but it is fixed in master now. If you encounter a similar bug, then please open a new issue so it's a little easier to track.

Thanks for finding all these little corner cases!
