### ISSUE TITLE
Cannot compile on fc27-32bit, "passTwoParseString" in Highlight.cpp 

### ISSUE THREAD

**Issue by insaner** [eteran/nedit-ng#117]
As mentioned in title, cannot compile on fc27-32bit, error as below:

```
/tmp/github/nedit-ng/src/Highlight.cpp: In static member function ‘static void Highlight::passTwoParseString(const HighlightData*, const char*, const char*, const char*, char*, int64_t, int*, const QString&, const char*, const char*)’:
/tmp/github/nedit-ng/src/Highlight.cpp:725:67: error: no matching function for call to ‘min(int, int64_t)’
      std::min(parseEnd - parseStart, length - (parseStart - string)),
                                                                    ^
```

Workaround was to edit both src/Highlight.cpp and src/Highlight.h to have the line:

`static void passTwoParseString(const HighlightData *pattern, const char *first, const char *last, const char *string, char *styleString, int length, int *prevChar, const QString &delimiters, const char *lookBehindTo, const char *match_to);`

instead of 

`static void passTwoParseString(const HighlightData *pattern, const char *first, const char *last, const char *string, char *styleString, int64_t length, int *prevChar, const QString &delimiters, const char *lookBehindTo, const char *match_to);`

(Replacing `int64_t` with just `int`).

Compilation succeeded, and I can run nedit-ng! (Amazing job on this project, I love it!)

**Comment by eteran** [comment]
Should be an easy fix. I'll look into it.

**Comment by eteran** [comment]
should be fixed in master.
