### ISSUE TITLE
-do argument not working

### ISSUE THREAD

**Issue by marilmanen** [eteran/nedit-ng#119]
This command works with nedit, but not with nedit-ng

    build/nedit-ng -do 'goto_line_number(58)' README.md

The macro command is silently ignored in nedit-ng

**Comment by eteran** [comment]
I will look into it!

**Comment by eteran** [comment]
Hmm, when I run that code here, it appears to work correctly. That is, line 58 is highlighted in the newly opened README.md.

Any other details you can include?

**Comment by eteran** [comment]
well, that's odd... suddenly, it isn't working when I tried it again! OK, looking deeper...

**Comment by eteran** [comment]
OK, this seems to be a race condition of some kind (macro being run before the document exists or something to that effect). For me, it works something like 1 out of 10 times. I'll see what I can do!
