### ISSUE TITLE
Another Modal dialog that shouldn't be

### ISSUE THREAD

**Issue by anjohnson** [eteran/nedit-ng#120]
Hi Evan,

This is similar to #43 but not one mentioned there: The Syntax Highlighting Patterns dialog is not modal in nedit, but currently is in nedit-ng.

Also just a request to add at least some of the Help topics if possible? I can never remember the syntax of the various parenthetical regex constructs so the regex section is one place I always have to look up in the Help, since it's sufficiently different to other regex engines. If you could use help converting and tweaking the text formatting you might be able to get that from some of your grateful users...

- Andrew

**Comment by eteran** [comment]
I'll definitely take a look at this. Thanks!

**Comment by sjtringali** [comment]
Yeah, having it modeless is a big way of writing the patterns and seeing how they apply immediately.

**Comment by eteran** [comment]
Just as a follow-up.

Using a modal dialog is a quick and easy way to prevent the user from messing with things while changes are still uncommitted. For example, what if they do something stupid like try to delete a language while the patterns dialog is open!

So yea, I'll work on making this non-modal, in the end, it's a one line fix, I just want to make sure that there is code to prevent user ... "creativity" from causing any problems.

**Comment by eteran** [comment]
Closing in favor of an issue that is a bit more comprehensive in listing dialogs that are modal in NG but not in NEdit5.

(See https://github.com/eteran/nedit-ng/issues/264)
