### ISSUE TITLE
horizontal scroll bar arrow click

### ISSUE THREAD

**Issue by marilmanen** [eteran/nedit-ng#124]
Is there a way to adjust the amount of horizontal movement when clicking the arrow icon on the horizontal scroll bar? Vertical scroll bar causes one line displacement and that's ok, but the horizontal scroll bar requires multiple clicks for a single character width.

**Comment by eteran** [comment]
Yes, it is definitely adjustable, however, I believe that the original nedit also horizontally scrolls by pixels and not characters.

That being said, I can look into how to best make this a configuration time option.

**Comment by marilmanen** [comment]
I just tested the old NEdit and with normal size font the scroll seems to be about one character. With very small font the scroll is more than one character and with very large font I need to click two times to get one character visible. With nedit-ng  I need to click 8 times to get one normal size character.

**Comment by eteran** [comment]
Ah, I bet in nedit the horizontal scrolling is by pixel, but the step for clicking the arrow is more than one. I'll check it out.

**Comment by eteran** [comment]
Yup, found it.

nedit tries its best to scroll by one character at a time. I can make a similar change to nedit-ng:

```
	XtVaSetValues(hScrollBar, XmNminimum, 0, XmNmaximum, 1,
    		XmNsliderSize, 1, XmNrepeatDelay, 10, XmNvalue, 0,
    		XmNincrement, fontStruct->max_bounds.width, NULL);
```

**Comment by eteran** [comment]
I think I have a fix ready to go (testing). I also think that your experience with nedit is actually slightly bugged. nedit only sets the step when it first creates the window to be the width of the character but doesn't change it when the font is changed as far as I can tell, which explains why when you changed the font size, you got different results.

**Comment by eteran** [comment]
Fix pushed to master, please re-open if you experience any other issues.
