### ISSUE TITLE
Move more complex settings to separate files?

### ISSUE THREAD

**Issue by eteran** [eteran/nedit-ng#139]
There are some settings that are particularly complex long strings of data that would be better off somehow separated out into files which the user could more directly edit if they choose. Some of these are effectively structured data that would be best represented in some sort of structured parsable format such as JSON/XML/etc.., others are things like user macros.

I'd like to look into storing these in separate files, perhaps using a directory structure for organization.

The settings in question are:

* `nedit.bgMenuCommands`
* `nedit.highlightPatterns`
* `nedit.languageModes`
* `nedit.macroCommands`
* `nedit.shellCommands`
* `nedit.smartIndentInit`
* `nedit.smartIndentInitCommon`

Ideally, this would be done in some sort of backward-compatible way, with the classical method being phased out at some point in a later version.

**Comment by anjohnson** [comment]
:+1: Suggest using [YAML](https://yaml.org/) for anything structured that should be user-editable (please don't use XML!). There are a few different versions with different library support, hopefully you'd only need the basic constructs which are easy to understand (some of the simpler YAML libraries for Perl don't support the more complex features since they are rarely used/needed).

**Comment by eteran** [comment]
@anjohnson Fair enough, XML is pretty terrible :-).

A good candidate for YAML is the `highlightPatterns` and `languageModes` as they are purely structured data. For the others which have potentially user-specified code... it's harder to come up with a good format.

I have considered something where the first line is a meta-data file, and the rest is the script

```
# Quote Mail Reply:::
if ($selection_start == -1)
    replace_all("^.*$", "\\> &", "regex")
else
    replace_in_selection("^.*$", "\\> &", "regex")
```

Or something to that effect. I'd like to be more structured than that, but we'll see what we can come up with I guess :-)

**Comment by eteran** [comment]
I think I have settled on a solution that will work perfectly! I plan to use the same idea of "Front Matter" from the Jekyll Blogging system (https://jekyllrb.com/docs/front-matter/).

The idea is that the file will have an initial YAML block between triple-dashed lines. Then the rest of the file can be the script code as normal:

So the above example would look like this, where all fields but the name are optional, which I think is pretty much ideal:

```
---
name: Quote Mail Reply
accelerator: Ctrl+Alt+Q
require_selection: false
---
if ($selection_start == -1)
    replace_all("^.*$", "\\> &", "regex")
else
    replace_in_selection("^.*$", "\\> &", "regex")

```
