### ISSUE TITLE
Qt's Tab widget introduces shortcuts that interfere with application shortcuts which use Alt

### ISSUE THREAD

**Issue by eteran** [eteran/nedit-ng#15]
When we create a tab. Qt "helpfully" create a keyboard shortcut for `ALT + QKeySequence::mnemonic(text)`.

Unfortunately, if we have any shortcuts which use ALT, they conflict with this :-(.

I can disable these shortcuts with event filtering, but they still "exist", so Qt will still consider them as creating ambiguity. I have not yet figured out a way to work around this besides not using ALT based shortcuts... which may in the end, be the ideal solution.

**Comment by boudewijnrempt** [comment]
I think that you can disable the automatic shortcuts with 
http://doc.qt.io/qt-5/qkeysequence.html#qt_set_sequence_auto_mnemonic

**Comment by eteran** [comment]
@boudewijnrempt Thanks!, that sounds like it'll work. I looked at QTabBar's code and it uses QKeySequence::mnemonic() in order to add the shortcuts.

**Comment by eteran** [comment]
@boudewijnrempt so this function **technically** works, but it also nukes just about every other shortcut in the app. I want all of theother shortcuts, just not the ones on the tabs...

I tried wrapping calls `to `addTab` and `setTabText` with disabling and enabling `qt_set_sequence_auto_mnemonic` before and after, but that didn't seem to work as I would have hoped.

There may be a fix here, I'll keep digging.

**Comment by boudewijnrempt** [comment]
Aw, that sucks...

**Comment by eteran** [comment]
After some digging, found out it was KDE's fault! Fixed!
