### ISSUE TITLE
crash with macro with shell_command in while loop

### ISSUE THREAD

**Issue by marilmanen** [eteran/nedit-ng#150]
I created a macro that will cause crash in nedit-ng, but not in nedit (it's a dummy modification of the real macro that I want to use)

open README.md in nedit-ng source directory, add following macro and execute it.  Select any on the LICENSE.md lines and pressing OK causes the crash. Selecting any of the README.md lines does not cause a crash.

```
matches = shell_command("grep -n and *.md", "")
selection = 1
while ( selection != "" ) {
  selection = list_dialog( "Select one", matches )
  if ( selection != "" ) {
    file = selection
    file = replace_in_string(file, ":.*", "", "regex")
    line = selection
    line = replace_in_string(line, ":\\D.*", "", "regex")
    line = replace_in_string(line, ".*:", "", "regex")
    if ( ( file == "" ) || ( line == "" ) ) {
        dialog("Something wrong with this macro: " selection "--" file "__" line, "OK")
    } else {
        open($file_path file)
        focus_window($file_path file)
        goto_line_number(line)
        matches = shell_command("grep -n and *.md", "")
    }
  }
}
```

**Comment by eteran** [comment]
Man, you are good at finding these corner cases! I'll check it out :-)

**Comment by eteran** [comment]
It should be fixed in master now. Please be advised that the latest in master has my YAML config file refactoring. It should auto-convert your config files as needed.

Please re-open this issue as needed :-).
