### ISSUE TITLE
removed setting functions (e.g. set_use_tabs)

### ISSUE THREAD

**Issue by mmorandi** [eteran/nedit-ng#154]
I used to have a smart tab rule for python, trying to move to space-based tab only for python, i.e.
```
$pyIndentDist = "default"
set_use_tabs(0)
```
for "Languace specific initialization macro" and
```
if (get_range($1-1, $1) != ":")
    return -1
return measureIndent($1) + defaultIndent($pyIndentDist)
```
for Newline Macro. Since https://github.com/eteran/nedit-ng/commit/1af84c46287489fea0ab2761b022a2453a553238 and the removal of ```set_use_tabs``` I do not have clear how this should be modified.

Thank you,

Marco

**Comment by eteran** [comment]
Ah, sorry for that inconvenience. What if each language mode was given the ability to override tab settings as it can for word delimiters and similar? I Feel like that's a better solution.

**Comment by mmorandi** [comment]
Yes, it would be definitely better!

**Comment by eteran** [comment]
OK, a new setting has been adding to the `$HOME/.config/nedit/languages.yaml`.

You were always able to have custom tab-stops per language, but now you can also control whether or not tabs are used at all.

Language mode section for python looks like this:

```
---
name: Python
extensions:
  - .py
delimiters: "!\"#$%&'()*+,-./:;<=>?@[\\\\]^`{|}~"
regex: ^#!.*python
wrap: None
indent: Auto
em_tab_distance: 4
insert_tabs: false
---
```

The last two lines are added from the defaults, and `insert_tabs` is a new capability.

`em_tab_distance: 4` means "when inserting a fake tab, use 4 spaces
`insert_tabs: false` means that for this language the "use tab characters in padding and emulated tabs" defaults to unset.

**Comment by eteran** [comment]
I plan to also add something for this new feature in the UI as well.

**Comment by anjohnson** [comment]
> now you can also control whether or not tabs are used at all.

Yay! Please set the default language mode setting for Makefiles to `insert_tabs: true`

**Comment by mmorandi** [comment]
Works like a charm. Thank you!

**Comment by eteran** [comment]
OK, Makefile now defaults to hardware tabs, python now defaults to emulated tabs, and now there is a UI for toggling it in the language modes dialog (it's a new tri-state checkbox that is one of yes/no/use global setting).

Closing this issue as we've implement a better solution than the original macro based one.
