### ISSUE TITLE
The building nedit on windows guide is incomplete

### ISSUE THREAD

**Issue by lester96** [eteran/nedit-ng#159]
Now Git also needs to be added as a dependency.  Also it would have been helpful if an approximate list of what Qt dependencies are needed to be added to get nedit to run outside of QtCreator. This latter would have saved me considerable time.

**Comment by eteran** [comment]
I'll see what I can do to improve it. Though the git dependency is kinda implicit given that you need git to check out the repo :-P

**Comment by lester96** [comment]
Actually, you can download the zip file without having Git installed.

**Comment by eteran** [comment]
Isn't that the only part of the build that REQUIRES got?

**Comment by lester96** [comment]
When I ran across it asking for it, I presumed it was related to the new help files. When I click on help, it opens a browser on github.

**Comment by eteran** [comment]
Yes, you certainly don't need a local install of git to use the help feature, it's just that the help docs are hosted by github pages.

**Comment by lester96** [comment]
OK, maybe it was from trying to use Visual Studio, which I tried at one point when I couldn't get a successful build (I had mismatched requirements). It probably was trying to check out the repo at that point.

**Comment by eteran** [comment]
I **think** this is effectively resolved as git isn't required to build. Please re-open if there is still a problem.
