### ISSUE TITLE
Escaping double % and # in shell commands

### ISSUE THREAD

**Issue by cgdae** [eteran/nedit-ng#163]
I think nedit-ng doesn't treat %% as % in shell commands, like nedit does.

I've attached a patch that fixes this, and also escapes ## in the same way.

[shell-commands-patch.txt](https://github.com/eteran/nedit-ng/files/4825104/shell-commands-patch.txt)

**Comment by eteran** [comment]
You are completely right, I'll take a look at the patch and see what I can do :-).

Thanks for the report!

**Comment by eteran** [comment]
Should be fixed in master now, thanks!
