### ISSUE TITLE
Setting nedit.heavyCursor=true leads to cursor droppings showing up occasionally

### ISSUE THREAD

**Issue by bogen85** [eteran/nedit-ng#165]
Since there is not block cursor I tried heavyCursor.
```
[General]
nedit.heavyCursor=true
nedit.textFont="Terminus (TTF),18,-1,5,50,0,0,0,0,0"
```
It looks OK, but does not cleanup after itself.

**Comment by bogen85** [comment]
```
$ nedit -version
nedit-ng version 2020.1

     Built on: Linux, x86_64, GCC 9.3.0
      With Qt: 5.12.8
   Running Qt: 5.12.8
       Locale: en
```

**Comment by eteran** [comment]
Hmm, yea, I want to implement a block cursor eventually (you'd be surprised how complex it ends up being due to the order of rendering).

But anyway, so it sounds like it doesn't fully refresh when the cursor is moved/blinks and leave a some pixels here and there?

**Comment by bogen85** [comment]
Correct.

At times it moves before it can clean up after itself so some pixels are left behind. Not all that often, but enough to make it so I won't use that feature.

**Comment by eteran** [comment]
Understood, I'll see what I can do. To be honest, I'd prefer to deprecate the feature in favor of a proper block cursor. But as mentioned, that's a bit more complex than it seems at first. But perhaps this issue will motivate me to put more effort into it ;-)

**Comment by bogen85** [comment]
Yeah, same here. As I stated earlier, I only tried heavyCursor because block cursor is not an option...

**Comment by bogen85** [comment]
I can close this if you don't have time to put the effort into. I would rather have heavyCursor deprecated as well and instead have a proper block cursor. Unless you just make this a low priority.

**Comment by bogen85** [comment]
I'm closing this issue, as I'd rather have the effort put into a full proper block cursor.
