### ISSUE TITLE
Window resize shows pixels, not columns x rows

### ISSUE THREAD

**Issue by bogen85** [eteran/nedit-ng#166]
I'm not sure what controls that any more, as I though it use to be the window manager.

Now for terminals I get columns x rows, on most apps I get nothing, but for nedit-ng I get X by Y pixels, which does not mean much.

It would be nice to have a visible margin like is some other text editors. Right now I'm using a "ruler.txt" file and I just resize the window.

Not high priority, as I use the "ruler.txt" work around...

**Comment by jabuzz** [comment]
There is a fix for this from two years ago now, though it is hidden somewhat. Works for me on Ubuntu 18.04LTS and 20.10

https://github.com/eteran/nedit-ng/issues/44

**Comment by eteran** [comment]
Sounds like this is not an issue anymore.

@bogen85 please re-open if it still is a problem.
