### ISSUE TITLE
Tabs settings not loaded from default

### ISSUE THREAD

**Issue by jlsantiago0** [eteran/nedit-ng#168]
I have the following in entries in my ~/.config/nedit-ng/config.ini related to tab configuration:

nedit.emulateTabs=3
nedit.insertTabs=false
nedit.tabDistance=3

Yes when i start nedit, the Preferences->Default Settings->Tab Stops ... is correct,
but the configured settings in Preferences->Tab Stops ... has different values. And I have to set them everytime I start the editor to get the settings I want.

I am using a build from the current master branch.

**Comment by eteran** [comment]
interesting... I'll take a look.

**Comment by eteran** [comment]
So I haven't been able to replicate this issue locally. For me both dialogs show 3, 3, and have emulate tabs checked. Is it possible that this was fixed and I don't recall doing it? LOL.

Also, is it possible that you have a language level setting that is overwriting the tab settings?

**Comment by jlsantiago0** [comment]
Hmm. I cant reproduce it now either.

**Comment by eteran** [comment]
sweet, I must have fixed it incidentally and not even realized that there was a ticket for it, LOL
