### ISSUE TITLE
load_macro_file in  autoload.nm causes Segmentation Fault

### ISSUE THREAD

**Issue by Rimpire** [eteran/nedit-ng#171]
I am using a group of macros called [Macro-Kit](http://www-evasion.imag.fr/Membres/Frank.Perbet/nedit/english_presentation.html) with my nedit. 

Tried to use the same Macro-Kit with nedit-ng but I am getting plain "Segmentation fault" message and nedit-ng crashes without any further details.

The setup of this MK adds load_macro_file($MK_ENV_VAR["MACRO_DIR"] "load_all_macros.nm") in the autoload.nm
I am not sure if load_macro_file is the reason for the crash, or further down the way.

**Comment by eteran** [comment]
I'll investigate ASAP!

**Comment by eteran** [comment]
OIK, reproduced locally. I'll post when I have it figured out

**Comment by eteran** [comment]
OK, traced it down to this (which is perfectly valid :-/)

```
$MK_ENV_VAR["HOME"] = getenv("HOME")
```

Seems that there is an issue with assigning the first value to an empty array. Should be easy to track down and fix... should be.

**Comment by eteran** [comment]
@Rimpire OK, fixed it! fortunately, it was just a silly mistake.

However, I can say that the script is expecting do be able to do something involving the `nc` command, so it may need other fixups. If I can figure them out without too much effort, I'll make a recomendation :-)

**Comment by eteran** [comment]
OK, it "loads cleanly" if you either:

1. make sure that `nc` is a symlink to `nc-ng` 
2. edit `macro_parameters.nm` and set line 29 to:

```
$mk_uc["nc"] = "nc-ng"
```

There's a comment there saying it's a common error.

If there is a particular feature of this macro kit that causes problems, please file another bug!
