### ISSUE TITLE
Mac Catalina build error

### ISSUE THREAD

**Issue by peiriannydd** [eteran/nedit-ng#174]
Hi, I have been waiting literally a decade to be able to use nedit on a mac.  I just tried @grege2 's wiki procedure, and when I tried the "cmake .." step from inside the nedit-ng-master/build directory, I got the error:

CMake Error at Util/CMakeLists.txt:3 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" (requested
  version 5.5.0) with any of the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.

-- Configuring incomplete, errors occurred!

I set
Qt5_DIR='/usr/local/opt/qt/lib/cmake/Qt5'
but that didn't help.  Unfortunately I'm not a computer programmer, I don't know what would solve this.  Any suggestions?  I am running MacOS 10.15.7.

**Comment by anjohnson** [comment]
My build process sets these environment variables before it runs cmake:
```
export BOOST_ROOT=/usr/local/Cellar/boost/1.74.0/
export Qt5_DIR=/usr/local/Cellar/qt/5.15.1
```
Adjust the actual paths as necessary. You might not need the first variable at all, but (assuming you installed that version of Qt5 using Homebrew) the second may fix your problem.

**Comment by peiriannydd** [comment]
Fantastic, that worked for me.  Thank you!
