### ISSUE TITLE
build failed on Windows 10 with GSL change

### ISSUE THREAD

**Issue by tksoh** [eteran/nedit-ng#179]
I was able to build nedit-ng on Windows 10 back in June by following the guide on the Wiki, using Qt 5.9.9 and VS 2019 community editor. However, after pulling in the latest change, the build failed with the errors, which seems to caused by the recent commit (I'm still able to build with the nedit-ng versions prior to that commit):

>  Using newer GSL
removing a bunch of unecessary casts

Here's the errors extracted from the compiler's output of Qt Creator.

> [51/136 1.7/sec] Building CXX object Interpreter\CMakeFiles\Interpreter.dir\prebuilt\parser.cpp.obj
FAILED: Interpreter/CMakeFiles/Interpreter.dir/prebuilt/parser.cpp.obj 
C:\PROGRA\~2\MICROS\~2\2019\COMMUN~1\VC\Tools\MSVC\1428\~1.293\bin\HostX86\x64\cl.exe  /nologo /TP -DPER_TAB_CLOSE -DQT_CORE_LIB -DQT_NETWORK_LIB -DQT_NO_CAST_FROM_ASCII -DQT_NO_CAST_TO_ASCII -DQT_NO_KEYWORDS -DUNICODE -DVISUAL_CTRL_CHARS -D_CRT_SECURE_NO_WARNINGS -D_SCL_SECURE_NO_WARNINGS -D_SILENCE_CXX17_UNCAUGHT_EXCEPTION_DEPRECATION_WARNING -D_UNICODE -IC:\Users\teeka\projects\nedit-ng\Interpreter -IC:\Users\teeka\projects\nedit-ng\Util\include -IC:\Users\teeka\projects\nedit-ng\Regex -IC:\Qt\5.9.9\msvc2017_64\include -IC:\Qt\5.9.9\msvc2017_64\include\QtCore -IC:\Qt\5.9.9\msvc2017_64\.\mkspecs\win32-msvc -IC:\Users\teeka\projects\nedit-ng\libs\GSL-3.1.0\include -IC:\Qt\5.9.9\msvc2017_64\include\QtNetwork -IC:\local\boost_1_73_0 /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MDd /Zi /Ob0 /Od /RTC1   -std:c++14 /showIncludes /FoInterpreter\CMakeFiles\Interpreter.dir\prebuilt\parser.cpp.obj /FdInterpreter\CMakeFiles\Interpreter.dir\Interpreter.pdb /FS -c C:\Users\teeka\projects\nedit-ng\Interpreter\prebuilt\parser.cpp
parser.y(446): error C2039: 'narrow': is not a member of 'gsl'
C:\Users\teeka\projects\nedit-ng\libs\GSL-3.1.0\include\gsl/span(59): note: see declaration of 'gsl'
parser.y(446): error C2065: 'narrow': undeclared identifier
parser.y(446): error C2062: type 'int' unexpected
parser.y(457): error C2039: 'narrow': is not a member of 'gsl'

Upgrading to latest version of VS does not help. Is there any changes required on the build setup? Appreciate if anyone can help point me to the right direction. Thanks.

**Comment by eteran** [comment]
Hmm, been a bit since I tried to build on windows, I'll take a look!

**Comment by eteran** [comment]
Ah, i see, it has to do with the prebuild bison parser files. I think I just need to update them.

**Comment by eteran** [comment]
Hopefully fixed in master, I'm going to close this, but please re-open if it is not fixed.
