### ISSUE TITLE
nc-ng fails to start.

### ISSUE THREAD

**Issue by ericxuo** [eteran/nedit-ng#18]
Hi,

Here is the error message I get when trying to run nc-ng (everything works fine with nedit-ng) : 

    # /mnt/Softs/local/nedit-ng/build/nc-ng
    nc: The server process failed to start. Either the invoked program is missing, or you may have insufficient permissions to invoke the program.

Any idea ?

Regards.

Xuo.

**Comment by eteran** [comment]
Let me look into this, my implementation uses Qt's local sockets instead of X based message passing. Is `nedity-ng` in your PATH? are you running as an ordinary user or as root?

Also, does the following work?

    nc-ng -svrcmd/mnt/Softs/local/nedit-ng/build/nedit-ng

(Assuming that's where your nedit-ng binary is as well)

**Comment by eteran** [comment]
BTW: thank you for feedback on this project! Nothing is ever perfect, but every little bit of feedback helps get things closer.

**Comment by ericxuo** [comment]
Hi,

No, nedit-ng was not in my path. I accessed it using a full path. As I considered it was still a debug process, I didn't add it in the PATH env var.
Yes , the command /mnt/Softs/local/nedit-ng/build/nc-ng -svrcmd /mnt/Softs/local/nedit-ng/build/nedit-ng
worked fine.
Then, I have added nedit-ng in the PATH env var and now running nc-ng works fine.

I am a great fan of nedit. So I'm glad to see other people working on it, and to help if I can.
By the way, I have a (stupid ?) question : it is painful to use nedit under Windows. Will nedit-ng be easier to use ?

Regards.

Xuo.

**Comment by eteran** [comment]
OK, so this seems to be simply a PATH issue. The original nedit uses the `system` libc function to execute the server, which also searches the PATH (as far as I know). So I'm going to close this bug. 

I suppose it is worth looking a good way to have it look for the nedit-ng binary in the same directory as the nc-ng binary if it's not in the PATH though.

Now, on to your question :-).

I plan for nedit-ng to have native support for running on both Windows and macOS! But it's not there yet, the code still has a few (relatively minor) usages of POSIX APIs that will need to be reworked. But you can expect that after the first major release, that I will have non-linux platforms in the works :-).
