### ISSUE TITLE
background color of space doesn't follow background color

### ISSUE THREAD

**Issue by peiriannydd** [eteran/nedit-ng#181]
In nedit-ng/theme.xml, the background color can be set with the line

 \<text background="#e2e2e2" foreground="black"/>

But the spaces do not follow the background color, they remain white:

![image](https://user-images.githubusercontent.com/73549725/99340270-5050d680-284d-11eb-9414-d52ee92f891f.png)

**Comment by peiriannydd** [comment]
Thank you so much for creating nedit-ng, I love nedit and wish I was a programmer, I would dive in and help with the work.

**Comment by anjohnson** [comment]
Do you have backlighting turned on (Preferences > Apply Backlighting)? If your config.ini has a `nedit.backlightCharTypes` setting for the char 32 that will overrule the theme.xml file background color for any space character. Try turning that off to start with and see if it makes any difference.

I find backlighting very useful for distinguishing spaces (char 32) from tabs (char 9), which can be important when programming. I set a slightly different backlight color for the two so the differences are apparent but not glaringly so.

**Comment by eteran** [comment]
@peiriannydd I believe that you have backlighting turned on. If you turn it off, then spaces (and other characters) will have only expected coloring.

Closing for now, Please re-open if I'm mistaken.

**Comment by peiriannydd** [comment]
Thank you, I never knew about backlighting, this is great!
