### ISSUE TITLE
Up-arrow to recall prev search, not working on MacOS

### ISSUE THREAD

**Issue by grege2** [eteran/nedit-ng#187]
Hi Evan,

On Mac the Up-Arrow key to recall a previous search, has never worked for me, in the Find and Find/Replace dialogs. This includes Catalina and Mojave, on several builds, from your latest tarball / zip. No combo of Cmd/Option/Contrl/Fn/Shift + Up-Arrow works either.

Env:
nedit-ng version 2020.1
     Built on: BSD4, x86_64, Clang 12.0 (Apple)
      With Qt: 5.15.1
   Running Qt: 5.15.1
       Locale: en-AU

The up-arrow (and down, left, right-arrow) work fine in other bindings, eg. as listed in Issue 185. And up-arrow or Prefix + up-arrow can be bound ok to an action in the Macros Dialog.

I've gone overboard with the info since you said somewhere you don't have good access to a Mac for testing :=( 

Cheers, Greg E

**Comment by anjohnson** [comment]
Ack, neither the Find Incremental box nor the Find dialog box currently support navigating the search history on Mac for me either. I thought I might have used it in the past but I can't guarantee that. I'm also currently using Qt 5.15.1 but used an earlier version before, so this might be a Qt thing.

**Comment by eteran** [comment]
I'll check into it, though not being a mac user, it may take me a bit to diagnose this one.

**Comment by grege2** [comment]
If it would help, if you get to a point where you're fairly sure you have a fix, I'm happy to try it here on Mac.

**Comment by grege2** [comment]
Hi, I've been trawling through the code, and Qt documentation. The text input widget (ie. the search text in the Find Dialog, a QLineEdit widget) does recognise Up-arrow and Dn-arrow, but actions them as "start of line" and "end of line". In the Qt QLineEdit doco page, https://doc.qt.io/qt-5/qlineedit.html ,  Home and End are listed against those actions, so I guess Mac Up-arrow and Dn-arrow have got translated to Home and End. I'm guessing you could disable that translation somehow, and collect Up-arrow and Dn-arrow as a raw event, then plug it into the Search History code, which all seems to be there. 

Just speculating here, this is guesswork from probing around a toolkit (Qt) that I don't know at all. I've sprinkled a few debug prints around to find my way. Ie. printf("here we are"), real sticks-and-stones debugging.

Does the "recall previous search" work ok on Linux ? 

I could fire up Qt Designer and build an app with one QLineEdit widget, and see how you can modify it, a bit of fun.

I could also put a Linux on my Mac with Parallels for Mac/Linux comparisons. I have an old Parallels Windows XP partition which is well overdue to be scrapped. Do you have any recommendation for a Linux that works well with Nedit-ng ?

Good news - I've been using nedit-ng in anger, made some substantial changes to my JavaScript code, all working well. Apart from the "recall prev search" issue above,  it's doing everything I need, excellent.  Much smoother than old X/Motif, goodbye to all that.

Ciao, GE.

**Comment by grege2** [comment]
Hi, 
I've made a quick hack to get something I can use, ie. a couple of keys that give me "step back" and "step forward" in the search history, in the Search Dialog box. These lines in DialogFind.cpp ..
```
		// only process up and down arrow keys
		if (event->key() != Qt::Key_Up && event->key() != Qt::Key_Down) {
```
are replaced by ..
```
		// only process "Substitute" up and down arrow keys
		if (event->key() != Qt::Key_Control && event->key() != Qt::Key_Alt) {
```
and of course a little further down we modify as follows ..
```
		// increment or decrement the index depending on which arrow was pressed
		// index += (event->key() == Qt::Key_Up) ? 1 : -1;     // old code
		index += (event->key() == Qt::Key_Control) ? 1 : -1;
```

My Command (Apple) key appears to generate Qt::Key_Control which is strange, but Option(Alt) generates Qt::Key_Alt as expected. These two codes seem not be used in any legitimate input in the Find Dialog text input field, so they're kind of free to be used as substitute Up_Arrow and Down_Arrow keys. Command and Alt are available on the right side of the Mac keyboard next to the arrow keys, so it's an easy substitution for the fingers. At a quick glance the same hack will be ok in the Find&Replace Dialog, in DialogReplace.cpp.

So, very hacky, and I would prefer to properly map the Up_Arrow and Down_Arrow Mac keys to these functions, but a very useable stopgap.

I will do the same in DialogReplace.cpp and report results.

Cheers, GE.

**Comment by grege2** [comment]
Done. The same changes work fine in the Replace dialog, ie. in DialogReplace.cpp. You have to change two areas, for each of the "text input" widgets, ie. the Find text and the Replace text. I even used "Previous Search" in the Find dialog to find the several places to edit in the Replace Dialog .. ahh, small pleasures.

I learned two new things I never knew ! 1) The Replace text can scroll independently of the Find text in the Replace Dialog 2) the find text from each Dialog (ie. Find and Replace) is shared between them, you can search for "abc" in the Find Dialog and it will appear as a find option when you scroll back in the Replace Dialog. Cool. I checked this always worked in the X/Motif version.

Well it's a bit of a hack - using an isolated Meta key press (Command and Alt) as a full "action key" is not great. I hope there's not a key combo that I haven't noticed, like Command+Something, which is now wrecked in the Find and Replace QLineEdit text widgets.

Cheers all.

**Comment by grege2** [comment]
Hi, just to be clear, my hack is working ok for me, so this can wait as long as you like. Cheers.

**Comment by eteran** [comment]
@grege2 awesome work, I may look into a configuration option to have an "alternate history navigation" or something like that if it can't be done with Up/Down.

I'm not sure why we can't capture them directly though... hmm.

**Comment by eteran** [comment]
@grege2 OK, I **may** have a solution that will "just work". Can you please check out the branch, https://github.com/eteran/nedit-ng/tree/macos-history-support

And let me know if it looks like it works in the **Find** dialog (I haven't touched replace yet, but it's the same concept).

If Find search history works for you in this branch, I'll apply the same fix to Replace and merge it in.

**Comment by grege2** [comment]
Great, I will check it out.

**Comment by grege2** [comment]
Hi, I've checked the mods, works fine for me. Up-Arrow and Down-Arrow step back / forward in the Search history, gives a bell when no more steps available, searches in "correct" direction (ie. fwd for Cmd-F, backwd for Shift-Cmd-F).  Cheers. 
(Catalina 10.15.7).

**Comment by eteran** [comment]
Awesome, I'll apply the fix to replace to and merge it into the master branch soon 👍

**Comment by eteran** [comment]
Should be all fixed in master!

**Comment by grege2** [comment]
Yep, downloaded and built the zipball, now Up-Arrow and Down-Arrow scroll back/fwd through the Find history in the Find Dialog, and the Find/Replace history in the Replace Dialog. And, which I never knew, the Find history is common to the Find and the Replace Dialog, could be handy. Cheers !

**Comment by anjohnson** [comment]
Up/down arrow now work in the Find dialog box, but not in the MainWindow's IFind box...

**Comment by eteran** [comment]
Ah, I'll have to add it there too! Reopening :-)

**Comment by eteran** [comment]
OK... **now** it should be fixed! Incremental search history navigation is now implemented in the same platform-agnostic way as the other search fields 👍

**Comment by grege2** [comment]
Hi, I checked it out, Up/Down arrow now work for me in the Incremental Find box, on Mac. I confess I've never used that :=( I think my nedit-ng usage is going to be more sophisticated than my nedit-X11 usage. Well, that's a fine thing.

**Comment by anjohnson** [comment]
Ack, thanks!
