### ISSUE TITLE
Order of macros with & without selection in macros.yaml affects Learn/Replay Keystrokes

### ISSUE THREAD

**Issue by grege2** [eteran/nedit-ng#189]
I seem to have discovered an issue in the order of macros saved in macros.yaml. Having a macro which requires a selection, at the top of macros.yaml, disables (greys out) the Learn/Finish/Cancel/Replay/Repeat group at the top of the Macro menu.

So, the following macros.yaml (1) keeps the Learn etc. group active ..
```
---
name: dummy test macro
command: |
  insert_string("abc")

---
name: make c++ comment
input: selection
command: |
  replace_in_selection("^.*$", "// &", "regex")

```
but the reverse order disables Learn etc.
```
---
name: make c++ comment
input: selection
command: |
  replace_in_selection("^.*$", "// &", "regex")

---
name: dummy test macro
command: |
  insert_string("abc")

```
The above is a minimal example, the same issue occurs with a much longer sequence of `input: selection` macros occurring before a sequence of "no selection" macros.

I've solved my own problem by having a dummy "no selection" macro at the top of macros.yaml, as per example (1) above.

Environment: Mac Catalina 10.5.7, 
nedit-ng version 2020.1
     Built on: BSD4, x86_64, Clang 12.0 (Apple)
      With Qt: 5.15.1
   Running Qt: 5.15.1
       Locale: en-AU

Also confirmed on latest tarball of 04 Dec. (I'm assuming the tarball is enough to get the latest code, and I don't need to clone a branch of the source, I'm not a big GitHub expert).

Cheers.

**Comment by eteran** [comment]
Thanks, I'll look into it

**Comment by eteran** [comment]
Confirmed, this is an interesting one! (I wonder if the original nedit has this problem?)

**Comment by eteran** [comment]
OK, I know the source of the bug, (and no, the original nedit did not have this issue, so sadly this is my fault ;-P).

I just have to figure out what the best solution is now.

**Comment by eteran** [comment]
Should be fixed in master. Note, I also fixed a related tiny bug where menu items that require a selection defaulted to enabled.

Now they will default to disabled and only become enabled once a selection is made.

Please re-open if the problem persists!

**Comment by grege2** [comment]
Thanks ! I will try it here as soon as I can. Cheers.

**Comment by grege2** [comment]
This has fixed the problem, thanks again.
