### ISSUE TITLE
Windows menu not showing list of documents correctly after detaching a document

### ISSUE THREAD

**Issue by tksoh** [eteran/nedit-ng#191]
Start nedit-ng, open three untitled documents, detach untitled_2, and we get:

1. on the windows for detached untitled_2, none of the documents are listed
2. on the original window (with untitled and untitled_1), only untitled and untitled_1 are listed.

screenshots attached. Using commit :

> commit b117490f488c1e241976fc1c48aeeded3014a70c (HEAD -> master, origin/master, origin/HEAD, eteran/master)
> Author: Evan Teran <evan.teran@gmail.com>
> Date:   Fri Dec 4 00:59:33 2020 -0500
> 
>     Minor formatting

![2020-12-08 11_38_47-Window](https://user-images.githubusercontent.com/494222/101437278-c7f4bb80-394a-11eb-9039-f1982cfcc668.jpg)
![2020-12-08 11_38_25-Window](https://user-images.githubusercontent.com/494222/101437283-c9be7f00-394a-11eb-9b67-d5307c5ebf7d.jpg)

**Comment by eteran** [comment]
Hmm, that's a weird one, I'll check it out ASAP!

**Comment by eteran** [comment]
Should be fixed in master (fortunately, this one looks like it was an easy one ;-P)
