### ISSUE TITLE
Unload Tags File menu not update after detaching document

### ISSUE THREAD

**Issue by tksoh** [eteran/nedit-ng#194]
This is probably related to issue  #191 

Steps to reproduce:

1. open some tabs
2. load a tag file
3. detach one of them => Unload Tag File menu is grayed out on the detached window.

![2020-12-09 17_34_18-Untitled_2](https://user-images.githubusercontent.com/494222/101611804-ee971d00-3a44-11eb-83cf-341127f349b9.jpg)

![2020-12-09 17_35_00-Untitled_2](https://user-images.githubusercontent.com/494222/101611834-f787ee80-3a44-11eb-96e8-84d32cbaec76.jpg)

**Comment by tksoh** [comment]
BTW, using nedit-ng version 2020.1-68-gb117490f

**Comment by tksoh** [comment]
Using nedit version 2020.1-71-gbe006b2e

**Comment by eteran** [comment]
Ok, yea makes sense. I'm not sure that I r call any code trying to sync that particular menu 😂

**Comment by tksoh** [comment]
My limited understanding is that MainWindow::updateMenuItems() tries to do that, but allWindows() skip over the new window because it's not yet visible. Apparently visibility is being used as a sign a window is being destroyed. Maybe that's not the best approach?

**Comment by eteran** [comment]
Ah yes, that makes sense.

I forget why, but there is a quirky reason for the "only visible" rule. I think it had to do with fixing a crash when a window that was about to be deleted was included in some things.

I'll see if there's a good refactor for that code to address this stuff more generally.

**Comment by eteran** [comment]
Should be fixed. I want to improve the fix at some point to make the code a little cleaner, but this will do for now. Please reopen if the problem persists
