### ISSUE TITLE
Open Previous menu not grayed out when empty

### ISSUE THREAD

**Issue by tksoh** [eteran/nedit-ng#198]
A really minor issue.

The Open Previous menu is not grayed out when there's no items in it. At worst, it might confuse new users ;-)

![2020-12-12 12_20_29-Untitled](https://user-images.githubusercontent.com/494222/101976088-c42fa480-3c7c-11eb-842f-7d56dc800fbd.jpg)

**Comment by eteran** [comment]
Fair enough :-)

**Comment by eteran** [comment]
Should be fixed in master!

please reopen if you the problem persists :-)
