### ISSUE TITLE
Feature Request: Open from Clipboard

### ISSUE THREAD

**Issue by anjohnson** [eteran/nedit-ng#205]
On the Mac (and potentially with Wayland on Linux I suspect) the current selection used for "Open Selected" is only available when the text is selected in a document that's currently open in Nedit-ng; in X11 because of how the selection worked that selection could be taken almost any other X11 application. What would be really useful as a close replacement for these newer systems would be "Open from Clipboard", where the file path has been copied from another application, which in my current case is the Mac Terminal. The rules should be the same so relative paths would be relative to the currently active document's directory. Is SHIFT+CTRL+Y currently available for the shortcut?

I suspect this wouldn't take too much effort to implement... (💥 / 💵 )

**Comment by grege2** [comment]
This sounds good.

**Comment by eteran** [comment]
So this is a slight challenge to do "right".

On Linux, it works, because on X11 we have access to the primary X selection, which occurs when things are highlighted. But on other platforms that don't use X11, we fake it the best we can... Which so far, this means that we work for selections in the document because we own that selection.

**Comment by anjohnson** [comment]
I'm just looking for something that does exactly the same as File-Open, Paste, Open, but without bringing up the dialog box. Am I confused about Qt's ability to access the contents of the clipboard?

**Comment by eteran** [comment]
So we can access the clipboard, but you'll have to do something like Ctrl+C or Cmd+C because while Qt does have access to the clipboard, bit doesn't have access to the selection on non-X11.

**Comment by eteran** [comment]
I think I have a solution.

We'll have a configuration option for `config.ini` that will make it use the clipboard instead of the selection? So anytime you have done like Cmd+C, then you can with a keyboard shortcut, open whatever filename is in clipboard currently?

**Comment by anjohnson** [comment]
Exactly, that should have been implied by my saying "Paste", I wrote my original description understanding the difference between the X11 selection (which Apple doesn't give you access to) and the clipboard (which it does).

I still find using the selection inside Nedit-ng helpful sometimes, so I was hoping for an extra command instead of replacing "Open Selection".

**Comment by eteran** [comment]
Yea, sorry I'm a little slow today :-P

**Comment by eteran** [comment]
I think perhaps binding this feature to "Ctrl+Shift+Y" or "Ctrl+Alt+Y" would not conflict with anything existing, would that work well for you?

**Comment by anjohnson** [comment]
Shift+Ctrl+Y (which on the Mac would become Shift+Cmd+Y) is perfect, thanks!

**Comment by eteran** [comment]
@anjohnson 

https://github.com/eteran/nedit-ng/pull/208

See if this works as you expect :-)
