### ISSUE TITLE
strace messages

### ISSUE THREAD

**Issue by marilmanen** [eteran/nedit-ng#210]
I had a feeling that there might be something wrong with my NEdit, so I did a dummy trial to check what it is doing. strace -p <pid> repeats printing 

poll([{fd=5, events=POLLIN}, {fd=8, events=POLLIN}, {fd=17, events=POLLIN}, {fd=18, events=POLLIN}], 4, 100) = 0 (Timeout)
recvmsg(8, 0x7fff703802f0, 0)           = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(8, 0x7fff70380310, 0)           = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=5, events=POLLIN}, {fd=8, events=POLLIN}, {fd=17, events=POLLIN}, {fd=18, events=POLLIN}], 4, 99) = 0 (Timeout)
recvmsg(8, 0x7fff703802f0, 0)           = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(8, 0x7fff70380310, 0)           = -1 EAGAIN (Resource temporarily unavailable)

even if the NEdit window (2020.1-98-g188c837) is inactive. Is this worth checking or is it expected behavior? I did a trial also with a new NEdit session and for that process the strace prints something only when I do something.

**Comment by eteran** [comment]
Hmm, I will take a look.I can say that there have been 7 commits since that version, and one of them addresses a possible "runaway timer" situation. Can you check with the latest master?

**Comment by eteran** [comment]
Also, I can say that 2020.1 release displays the same behavior on strace (that is routine polling) and that there certainly isn't any code in nedit itself deliberately triggering polling, and that if I were to guess, it is likely the Qt event pump running and usually, not receiving a new message.

**Comment by marilmanen** [comment]
OK, I had also an issue with my setup and that's why I was using old version. Now I'm using the latest and I think this issue should be closed.

**Comment by eteran** [comment]
No worries will close :-).

Your usage pattern definitely seems to identify interesting corner cases in the code, so I really appreciate your feedback and sticking with nedit-ng while I iron them all out! So please do keep em coming.

Let me know if some of your other issues are addressed in the recent work too!
