### ISSUE TITLE
new split pane always start displaying from line #1

### ISSUE THREAD

**Issue by tksoh** [eteran/nedit-ng#239]
when creating a a new split pane, the new pane always starts displaying from first line. Nedit classic would scroll the new pane to match the original pane.

![2021-01-02 14_57_15-Window](https://user-images.githubusercontent.com/494222/103452556-cf21a600-4d0b-11eb-8783-92a298babf37.jpg)

**Comment by eteran** [comment]
A good find! I think this should generally be an easy fix :-)

**Comment by eteran** [comment]
Merged in a general fix!

There is one quirk to it, and it's not easy to address at all. Basically, there is no obvious way in Qt to know which of a split pane is the "active one" So this patch simply scrolls to where the first pane is (I think the vast majority of the time people are looking for 2 panes, so this is typically the right behavior).

So I'll have to leave this issue open as "mostly fixed" until I discover a means to detect which pane the user is working in when they make the request to split panes.

**Comment by tksoh** [comment]
On Windows 10, I am getting a crash if I load a file, scroll down a few line, split. Have not tried on Linux.

Here's the Application output of Qt Creator:

> 17:19:41: Starting C:\Users\teeka\projects\nedit\build-nedit-ng\nedit-ng.exe -server...
> Debug: Loading "C:\Users\teeka\QtProject\qtlogging.ini" ... (io\qloggingregistry.cpp:282, loadRulesFromFile)
> Fatal: ASSERT failure in QVector<T>::operator[]: "index out of range", file C:\Qt\5.9.9\msvc2017_64\include\QtCore/qvector.h, line 431 (C:\Qt\5.9.9\msvc2017_64\include\QtCore/qvector.h:431, (null))
> 17:20:28: The program has unexpectedly finished.
> 17:20:28: The process was ended forcefully.
> 17:20:28: C:\Users\teeka\projects\nedit\build-nedit-ng\nedit-ng.exe crashed.
> 

![2021-01-02 17_20_11-Window](https://user-images.githubusercontent.com/494222/103454510-e5d1f800-4d1f-11eb-986f-86519bae29db.jpg)

**Comment by eteran** [comment]
Well, that's not good! LOL

The weird thing is that `QVector` is used in so few places and none of them are really related to the split pane stuff.

Could you try a fresh rebuild (clear out the build directory first), could it be a strange issue with a mix of new code and old code being linked together somehow?

**Comment by eteran** [comment]
OK, built on windows and have replicated locally. Investigating...

**Comment by eteran** [comment]
Should be fixed in master now that I have merged https://github.com/eteran/nedit-ng/pull/242

**Comment by eteran** [comment]
Please reopen if this problem continues
