### ISSUE TITLE
Unable to assign shortcut keys to macros

### ISSUE THREAD

**Issue by lester96** [eteran/nedit-ng#241]
I have a lot of macros that I used with NEdit-5 that had shortcut keystrokes assigned with an Alt-key. None of these shortcuts work now, to use the macros I have to click on entries in the macro menu. Even the learn macro shortcut, which was Alt-K does not work. I am running Linux with a KDE desktop, if that matters.

**Comment by eteran** [comment]
Assigning shortcut keys to macros certainly should work, and I can say that Alt+K works locally for me on KDE, so I have a few questions to help get to the bottom of this.

1. For your macros, does it show the shortcut next to the menu items?
2. For manually assigning accelerators in the macro commands menu, do you see the accelerator shortcut in the accelerator textbox?
3.Are you SURE it is all shortcuts do is it just bad luck that you have tested with ones that conflict with standard menu navigation (like Alt+F should bring down the file menu)
4. Can you send me a tar of your ~/.config/nedit-ng directory for me to test locally?

**Comment by eteran** [comment]
@lester96 By any chance are all the shortcuts you are testing on the "window background" (aka context) menu? I just noticed a quirk with Qt where that doesn't work out of the box.

**Comment by eteran** [comment]
@lester96 Any chance you can follow up on this so I can investigate futher?

**Comment by lester96** [comment]
I forgot to close this. The problem was not nedit, but my window manager (KDE). There is (was) some combination of key assignments for KDE functions that disabled using ALT as a modifier. I did unscramble the combination at the time, so that I could use ALT, but then just switched all my key assignments to use META, which worked fine. I haven't tried ALT in quite awhile, and the desktop management has changed considerably, so the problem may not even exist anymore. I am closing this.

**Comment by eteran** [comment]
Thanks!
