### ISSUE TITLE
incorrect tab position and misalignment in macro editing text widget

### ISSUE THREAD

**Issue by tksoh** [eteran/nedit-ng#251]
Just noticed something strange in macro editor:

1. Tab seems to expand to somewhere between 12 to 13 spaces, instead of 8.
2. The text ("AAA") after a tab charactor does not aligned properly

Note:
- backlighting is ON in the main editor (tab is shown as darker gray)
- using version 2020.1-137-ge5143422 on Windows 10 with Qt 5.9

![2021-01-05 09_35_56-Macro Commands](https://user-images.githubusercontent.com/494222/103596736-8f400600-4f39-11eb-95c7-a19b2861d59d.jpg)

**Comment by eteran** [comment]
My guess is that this is a font issue. I'll take a look and see what the story is.

But I can say that this is yet more motivation for using the macro editor to be the same widget as the main text editor.

**Comment by tksoh** [comment]
> But I can say that this is yet more motivation for using the macro editor to be the same widget as the main text editor.

That'd be nice.

Perhaps we can also think about letting users develop macro using the main editor. I actually have a patch for nedit 5 to do that, but it requires changes to the macro language (mainly on assigning menu and shortcut) in order to fully support that, so its usefulness is kind of limited at the moment. But it's another idea to consider. The use of YAML files in NG might make things easier.

**Comment by tksoh** [comment]
This is how my patch looks like...

![2021-01-05 11_11_22-toshiba (tksoh-Satellite-L645_1 (tksoh)) - VNC Viewer](https://user-images.githubusercontent.com/494222/103602396-e5677600-4f46-11eb-90e1-f38badd5a71c.jpg)

**Comment by eteran** [comment]
Cool, I can imagine a UI where for a macro you just click on "edit" and it opens up a new NEdit tab, you edit the file and save it and it automatically gets saved into the macro settings seemlessly.

**Comment by tksoh** [comment]
Perhaps we could just edit the yaml file in the main editor, and parse it to update as we hit save/apply. We do need to be able to tell the yaml is for macros.

**Comment by eteran** [comment]
Should be fixed in master, closing!
