### ISSUE TITLE
Error when building under OS2

### ISSUE THREAD

**Issue by TeLLie** [eteran/nedit-ng#252]
Hello,
I tried to compile with OS2
I use cmake 3.15.3 and gcc v9.2.0 and Qmake v5.13.1
Make failed with a lot of errors like:

[ 78%] Building CXX object src/CMakeFiles/nedit-ng.dir/HighlightPatternModel.cpp.o
E:/qt5-src/nedit-ng/src/DocumentWidget.cpp: In member function 'void DocumentWidget::checkForChangesToFile()':
E:/qt5-src/nedit-ng/src/DocumentWidget.cpp:2070:13: error: 'using element_type = struct DocumentInfo' {aka 'struct DocumentInfo'} has no member named 'mode'
 2070 |  if (info_->mode != statbuf.st_mode || info_->uid != statbuf.st_uid || info_->gid != statbuf.st_gid) {
      |             ^~~~
E:/qt5-src/nedit-ng/src/DocumentWidget.cpp:2070:47: error: 'using element_type = struct DocumentInfo' {aka 'struct DocumentInfo'} has no member named 'uid'
 2070 |  if (info_->mode != statbuf.st_mode || info_->uid != statbuf.st_uid || info_->gid != statbuf.st_gid) {
      |                                               ^~~
E:/qt5-src/nedit-ng/src/DocumentWidget.cpp:2070:79: error: 'using element_type = struct DocumentInfo' {aka 'struct DocumentInfo'} has no member named 'gid'
 2070 |  if (info_->mode != statbuf.st_mode || info_->uid != statbuf.st_uid || info_->gid != statbuf.st_gid) {
      |                                                                               ^~~
E:/qt5-src/nedit-ng/src/DocumentWidget.cpp:2072:10: error: 'using element_type = struct DocumentInfo' {aka 'struct DocumentInfo'} has no member named 'mode'
 2072 |   info_->mode = statbuf.st_mode;
      |          ^~~~
E:/qt5-src/nedit-ng/src/DocumentWidget.cpp:2073:10: error: 'using element_type = struct DocumentInfo' {aka 'struct DocumentInfo'} has no member named 'uid'
 2073 |   info_->uid  = statbuf.st_uid;
      |          ^~~
E:/qt5-src/nedit-ng/src/DocumentWidget.cpp:2074:10: error: 'using element_type = struct DocumentInfo' {aka 'struct DocumentInfo'} has no member named 'gid'
 2074 |   info_->gid  = statbuf.st_gid;
      |          ^~~
E:/qt5-src/nedit-ng/src/DocumentWidget.cpp: In member function 'bool DocumentWidget::saveDocumentAs(const QString&, bool)':
E:/qt5-src/nedit-ng/src/DocumentWidget.cpp:2636:9: error: 'using element_type = struct DocumentInfo' {aka 'struct DocumentInfo'} has no member named 'mode'
 2636 |  info_->mode     = 0;
      |         ^~~~
E:/qt5-src/nedit-ng/src/DocumentWidget.cpp:2637:9: error: 'using element_type = struct DocumentInfo' {aka 'struct DocumentInfo'} has no member named 'uid'
 2637 |  info_->uid      = 0;
      |         ^~~
E:/qt5-src/nedit-ng/src/DocumentWidget.cpp:2638:9: error: 'using element_type = struct DocumentInfo' {aka 'struct DocumentInfo'} has no member named 'gid'
 2638 |  info_->gid      = 0;
      |         ^~~
E:/qt5-src/nedit-ng/src/DocumentWidget.cpp: In member function 'void DocumentWidget::closeDocument()':
E:/qt5-src/nedit-ng/src/DocumentWidget.cpp:2958:10: error: 'using element_type = struct DocumentInfo' {aka 'struct DocumentInfo'} has no member named 'mode'
 2958 |   info_->mode        = 0;
      |          ^~~~
E:/qt5-src/nedit-ng/src/DocumentWidget.cpp:2959:10: error: 'using element_type = struct DocumentInfo' {aka 'struct DocumentInfo'} has no member named 'uid'
 2959 |   info_->uid         = 0;
      |          ^~~
E:/qt5-src/nedit-ng/src/DocumentWidget.cpp:2960:10: error: 'using element_type = struct DocumentInfo' {aka 'struct DocumentInfo'} has no member named 'gid'
 2960 |   info_->gid         = 0;
      |          ^~~
E:/qt5-src/nedit-ng/src/DocumentWidget.cpp: In member function 'bool DocumentWidget::doOpen(const QString&, const QString&, int)':
E:/qt5-src/nedit-ng/src/DocumentWidget.cpp:3226:10: error: 'using element_type = struct DocumentInfo' {aka 'struct DocumentInfo'} has no member named 'mode'
 3226 |   info_->mode        = statbuf.st_mode;
      |          ^~~~
E:/qt5-src/nedit-ng/src/DocumentWidget.cpp:3227:10: error: 'using element_type = struct DocumentInfo' {aka 'struct DocumentInfo'} has no member named 'uid'
 3227 |   info_->uid         = statbuf.st_uid;
      |          ^~~
E:/qt5-src/nedit-ng/src/DocumentWidget.cpp:3228:10: error: 'using element_type = struct DocumentInfo' {aka 'struct DocumentInfo'} has no member named 'gid'
 3228 |   info_->gid         = statbuf.st_gid;
      |          ^~~
[ 79%] Building CXX object src/CMakeFiles/nedit-ng.dir/HighlightStyleModel.cpp.o
[ 80%] Building CXX object src/CMakeFiles/nedit-ng.dir/KeySequenceEdit.cpp.o
[ 81%] Building CXX object src/CMakeFiles/nedit-ng.dir/LanguageModeModel.cpp.o
make[2]: *** [src/CMakeFiles/nedit-ng.dir/DocumentWidget.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/CMakeFiles/nedit-ng.dir/all] Error 2
make: *** [all] Error 2
[E:\qt5-src\nedit-ng\os2]

Anny idea how to fix those errors??

**Comment by eteran** [comment]
Oh wow, an OS2 user, I've never met one! Thanks for giving NEdit-NG a try :-).

So I can definitely put in a patch to fix those specific errors, windows needed a similar patch. However, I can say that I have NO ability to test things against OS2. So I'll be flying a little bit blind.

But, we'll see what we can do, and if you're willing/able to work with me a little bit back and forth, hopefully, we can get it fully compiling and working. (I do suspect that there are other small details that will be sensitive to OS2 differences, for example, getting the user data comes to mind).

**Comment by TeLLie** [comment]
Hi,
Im pleased to help, in what way :)
So i'm ready

**Comment by eteran** [comment]
@TeLLie Awesome. So I've started a download for OS2WARP4 from WinWorld, so that MAYBE I'll be able to run it in a VM. But I'm about to start my work day. I'll push  a patch for the specific errors you are seeing later today, and we can go from there!

I see that you have qt5 built for OS2, which is pretty awesome since as far as I know, it's not officially supported (Qt doesn't define a macro targetting it here https://doc.qt.io/qt-5/qtglobal.html#Q_OS_AIX)

**Comment by TeLLie** [comment]
Hi 
Nope it's  not official in the QT repo
But we use as a macro Q_OS_OS2)
look @ arcanoae.com for the latest info as warp4 is way to old

**Comment by eteran** [comment]
Very cool, I'll check it out later. Is the Qt port open source where I can look at how some things were implemented? That may help!

**Comment by TeLLie** [comment]
Hi,
Most software that is ported to OS2 you will almost fine here...
https://github.com/bitwiseworks
https://github.com/bitwiseworks/qt5-os2

**Comment by TeLLie** [comment]
But the Qt5 port is not ported 100% yet
They now porting the chrominium part, as there just a few peeps that are porting stuff to OS/2

**Comment by eteran** [comment]
@TeLLie Cool. So I have a plan to fix this particular set of errors. Since Qt for OS/2 is unfinished, that of course doesn't garauntee that NEdit-NG will work. But we'll slowly try. I'll post here when I've patched it. I've got some other stuff in flight, so it may be a few days though

**Comment by TeLLie** [comment]
Hi
That's fine with me..
I wait for the patches 🥺
Thankz so far for the help👍

Op do 7 jan. 2021 03:47 schreef Evan Teran <notifications@github.com>:

**Comment by TeLLie** [comment]
Hi eteran,
Thankz that fixed it.
It's running further now.
Now its failing with:
E:/qt5-src/nedit-ng/src/userCmds.cpp:469:25: error: 'defaultMenu' was not declared in this scope
  469 |    menu = YAML::LoadAll(defaultMenu.data());
I fixed this with:
#elif defined(Q_OS_OS2)
			static QByteArray defaultMenu = loadResource(QLatin1String("DefaultShellMenuOs2.yaml"));
Now its compiling to the end :P

But when starting the prog it crashes :(

E:\qt5-src\nedit-ng\os22>nedit-ng.exe 2>&1 |tee run.out
Fatal: Failed to load internal resource

Killed by SIGABRT
pid=0x0bb1 ppid=0x0bb0 tid=0x0001 slot=0x00ba pri=0x0200 mc=0x0001 ps=0x0010
E:\QT5-SRC\NEDIT-NG\OS22\NEDIT-NG.EXE
Process dumping was disabled, use DUMPPROC / PROCDUMP to enable it.

i get with cmdline version:
E:\qt5-src\nedit-ng\os22>nc-ng.exe -version
nc-ng (nedit-ng) Version 2020.1

Built on: OS/2, x86, GCC 9.2.0 20190812 (OS/2 RPM build 9.2.0-5.oc00)

Any idea about the line
Fatal: Failed to load internal resource

**Comment by eteran** [comment]
Gotcha, I think that's easy to fix 👍

**Comment by eteran** [comment]
@TeLLie 

Yea, so while you change will make it compile, the resource you set it to doesn't actually exist in nedit, so it will just fail at runtime when it tries to load it (as you observed). But... I just made it so when compiling for an unknown OS, it will just default to an empty set, which seems sensible considering that this is for the OS-specific shell menu.

See if that helps!

**Comment by TeLLie** [comment]
Hello,
Thankz again this fixed it :)
now its starting but i see "Warning: NEdit: a variable width font has been specified. This is not supported, and will result in unexpected results"
Is this from any harm?
Thankz so far for all

**Comment by eteran** [comment]
Variable width fonts won't "break" anything, but will cause some things to not render correctly.

So ideally, you'll be able to find a fixed width font that looks good for your needs.

Closing this issue because we got it working!
