### ISSUE TITLE
macro editor issue

### ISSUE THREAD

**Issue by tksoh** [eteran/nedit-ng#260]
This probably has something to do with our earlier discussion #244.

Using nedit-ng version 2020.1-152-g74ab961e on master.

When I deleted a macro right above the Push Tag macro, it somehow got turned into Pop Tag. Here's the sequence:

1. Before deleting 'tag test' macro:

![2021-01-10 11_46_57-toshiba (tksoh-Satellite-L645_1 (tksoh)) - VNC Viewer](https://user-images.githubusercontent.com/494222/104114097-6e155600-533b-11eb-9384-ae4eb31d46da.jpg)

2. After deleting 'tag test' macro. Notice the Menu Entry field and command editor now showing 'Pop Tag' , even though the list window still showing 'Find Tag"

![2021-01-10 11_48_04-toshiba (tksoh-Satellite-L645_1 (tksoh)) - VNC Viewer](https://user-images.githubusercontent.com/494222/104114100-71104680-533b-11eb-86e4-be92a59e9e9c.jpg)

3. After clicking "Apply". There are not two copy of 'Pop Tag' entries.

![2021-01-10 11_48_31-toshiba (tksoh-Satellite-L645_1 (tksoh)) - VNC Viewer](https://user-images.githubusercontent.com/494222/104114103-740b3700-533b-11eb-98cd-570cd7608233.jpg)

**Comment by eteran** [comment]
Hmm, that's a weird one for sure. Out of curiosity. Are you able to replicate it starting with a fresh config?

I ask because the previously referenced discussion was technically "cosmetic", in that the macros were not really deleted, they just weren't being displayed.

So I'm wondering if you efforts to work around that bug and recreate your macros put things in a weird state.

**Comment by eteran** [comment]
OK, I think this is another "cosmetic" issue. It appears that things are just getting slightly out of sync.

I was able to reproduce what you saw (so no, it wasn't related to anything you did). But afterwards, if I clicked on another entry and then back on the one with the wrong contents, it showed the correct data.

So the issue appears to be that after a delete, it is selecting one entry, but displaying another's data. Hopefully a simple fix :)

**Comment by eteran** [comment]
In fact all 3 dialogs of this type have this bug. Looking into it...

**Comment by eteran** [comment]
@tksoh I **think** that this PR should fix that issue (in all 3 dialogs since I made them share a lot of code):

https://github.com/eteran/nedit-ng/pull/261

**Comment by tksoh** [comment]
I tested the macro editor seems to be ok now. I presume the other dialogs would be ok too ;-)
