### ISSUE TITLE
nc-ng do command tab change

### ISSUE THREAD

**Issue by marilmanen** [eteran/nedit-ng#263]
When opening two files with `nc-ng -svrname test f1 f2` and then executing command `nc-ng -svrname test -do 'goto_line_number(2)'` the tab selection switches to file f1 and selects line 2. With old NEdit the tab does not change and the macro selects line 2 from file f2. This is minor issue as workaround is to define also the file name in the nc-ng command and not rely on the currently active tab.

**Comment by eteran** [comment]
So according to the comments in the NEdit 5.7.

A do command with an empty filename means "choose a random window for executing the -do macro". So I'm unsure if this is a real bug since it was never guaranteed to be any particular window.

**Comment by grege2** [comment]
Hi, this intrigued me so I tested on Mac. Yes, without a filename, the goto happens in the first tab, whatever it is, and no matter which tab is currently selected. With a filename it goes to the requested file/tab. But I've never used the `-do` facility so I don't have an assumption about it.

I guess there are a few neat tricks like this. I suppose opening a file or tab at a specific line number is pretty basic, eg. you're chasing a reported compile error at line nnnn. And it's already catered for in the `-line` command-line option. But I guess there a lot of neat tricks that can be rolled up in a `-do [some macro stuff]`.  They would be focused on "initialisation" shortcuts. But they could be complete file-wide edit actions, ie. open file, change all xxx to yyy. Maybe we could start a page in the Wiki on these types of tips.

**Comment by eteran** [comment]
@grege2 correct, if you are using `nc`, basically you can automate nearly any operation via the command line and macros :-).

The main thing to note is that if you intend to target a specific document, your command should say so as the variant with no filename specified simply "picks a document" (I believe that NG just picks the "first" document since it's as good a choice as any other).

**Comment by marilmanen** [comment]
Specifying the filename is the correct approach, so I think that this is not an issue and should be closed.
