### ISSUE TITLE
nc -wait times out

### ISSUE THREAD

**Issue by sjtringali** [eteran/nedit-ng#268]
I use 'nc -wait' with the server to edit files for integration into various tools. Often, it times out even though the window or tab is still open.

The server timeout should only be for waiting to contacting the server and getting a reply, otherwise it should wait forever.

Expected behavior: nc waits forever until the document is closed.

**Comment by eteran** [comment]
@sjtringali are you using the latest master. A week or so ago, I pushed a fix for it timing out after 30 seconds. Now it is SUPPOSED to wait indefinitely until the document closes.

**Comment by sjtringali** [comment]
Heh you might be fixing things faster than I can report them... I’ll check tomorrow.

**Comment by eteran** [comment]
@sjtringali When you get a chance, could you confirm that this is either fixed or still a problem for you?

Thanks!

**Comment by eteran** [comment]
@sjtringali Closing due to lack of follow-up and my belief that this is already fixed. Please do re-open if the problem persists though!
