### ISSUE TITLE
long highlight pattern cannot check/apply/save

### ISSUE THREAD

**Issue by tksoh** [eteran/nedit-ng#271]
I tried to create a highlighting pattern with very long regexp string, and has the following observation:

- click on 'Check' => no dialog to tell if the pattern is ok/error
- click on 'Apply' => the matching texts are not highlighted (line 7 in editor)
- click on 'OK' => dialog will not close
- click on 'Close' => dialog closes, but pattern is discarded
- exact same pattern works fine on nedit 5

Pattern used: [cmake_property_pattern.txt](https://github.com/eteran/nedit-ng/files/5801089/cmake_property_pattern.txt)

![2021-01-12 17_28_55-Window](https://user-images.githubusercontent.com/494222/104296419-8d0f1600-54fc-11eb-9f49-f281b5b9317a.jpg)

**Comment by tksoh** [comment]
BTW, there's another even longer pattern appeared to be working ok on NG somehow.

[cmake_variable_pattern.txt](https://github.com/eteran/nedit-ng/files/5801118/cmake_variable_pattern.txt)

**Comment by eteran** [comment]
OK, that's an interesting one. I'll check into it. Thanks for providing the patterns, that will help a lot in reproducing it.

**Comment by tksoh** [comment]
@eteran FYI, the working pattern highlights the red color CMAKE_xxx_xxx text on line 3-6.

**Comment by eteran** [comment]
@tksoh This is a weird one. So I'm having a hard time reproducing locally, and when I look at the code path for the "check" button, it's pretty straight forward. I don't really see a code path that is both a failure and is silent :-/. 

Also, for me, that pattern does highlight `CMAKE_CONFIGURE_DEPENDS`.

**Comment by tksoh** [comment]
I am puzzled how it could behave differently on your system. When I saw the error, it was on Windows. I will try it out on Linux later to confirm.

**Comment by eteran** [comment]
@tksoh me too. I was testing on windows too!

**Comment by tksoh** [comment]
OK. I know what I missed. 

Actually, we needed to have both long patterns added to the language at the same time. I added both patterns into patterns.yaml manually, the start nedit-ng and load a cmake file, which gave me this message:

> Warning: NEdit: Error compiling syntax highlight patterns:
> Regex > 32767 bytes

And the cmake file does not get highlighted. Regex limit aside, nedit-ng should report that error when we click 'Click'.

Then we need make a decision on the regex limit.

**Comment by tksoh** [comment]
If I added the second pattern (property) on the pattern dialog (where the first pattern already added prior to the second) and click 'Check', I could see the error message on Qt Creator's Application Output area:

> Warning: QKeySequence::mnemonic: "S&ub-pattern (processed within start & end of parent)" contains multiple occurrences of '&'
> Warning: NEdit: Error compiling syntax highlight patterns:
> Regex > 32767 bytes

So, NG is able to catch the error, but just not reporting at the right place -- we need the error dialog.

I am not sure what the sub-pattern warning is about, since the patterns don't use sub-pattern.

**Comment by eteran** [comment]
So right now, the regex limits are pretty ha d coded. They are a result of the "branch" instructions being 16-bits.

I have a branch tracking my work to refactor the regex engine, but it's gonna involve a lot of work and even more testing before it's ready.

**Comment by eteran** [comment]
Oh also, the pattern warning is probably my error, I think that may be a slight mess up when I added a keyboard accelerator to that dialog.

**Comment by eteran** [comment]
@tksoh one piece of advice on shortening that regex is to collapse common prefixes as much as you can.

For example, this segment (picked mostly at random):

```
ARCHIVE_OUTPUT_NAME|ARCHIVE_OUTPUT_NAME_\w+
```

can be re-written as:

```
ARCHIVE_OUTPUT_NAME(?:_\w+)?
```

Which as you can see is nearly half the length. Doing this across the whole regex can save a LOT of bytes in the long run.

----

Just in case some of the syntax is slightly unfamiliar to you, I'll explain (ignore this part if you are very familiar with regexes):

`(?:` is the opening of a non-capture group, it will group as normal, but doesn't ask the regex engine to track what was inside of it for the results:

`_\w+` This is the part you wrote, (and underscore followed by one or more word characters)

`)?` End the capture group, and say that the group must match 0 or 1 times. In other words, it is optional.

**Comment by eteran** [comment]
> Warning: QKeySequence::mnemonic: "S&ub-pattern (processed within start & end of parent)" contains multiple occurrences of '&'

This warning should be fixed in master now. Whoops :-P

**Comment by tksoh** [comment]
> > Warning: QKeySequence::mnemonic: "S&ub-pattern (processed within start & end of parent)" contains multiple occurrences of '&'
> 
> This warning should be fixed in master now. Whoops :-P

Looks good

**Comment by tksoh** [comment]
> @tksoh one piece of advice on shortening that regex is to collapse common prefixes as much as you can.

The patterns are just quick and dirty conversion from the output of 'cmake --help-property-list' and '--help-variable-list'. Since it's a long list of about 500+ lines each, I didn't try to optimize it manually. I could, but I am not sure it's sustainable. I am considering if these patterns are critical enough to be included.

At least I now know what the limit nedit is on this topic ;-) 

> Just in case some of the syntax is slightly unfamiliar to you, I'll explain (ignore this part if you are very familiar with regexes):

I can't say I'm an expert, but 20 years with Perl, I do know a thing or two about regexp ;-)

**Comment by tksoh** [comment]
> This warning should be fixed in master now. Whoops :-P

@etaran  As we discussed in the other thread, we can't rely on the printout on the terminal/console. Can we add a dialog for the errors?

**Comment by eteran** [comment]
@tksoh yea the one harmless warning is gone. I do plan to elevate the fatal error to a message box 👍

**Comment by eteran** [comment]
Looking good, a patch in nearly ready :-)

![image](https://user-images.githubusercontent.com/571477/104794618-c357ca00-5776-11eb-88c3-233b8d5c7c00.png)

**Comment by eteran** [comment]
@tksoh this dialog should now be non-modal and report regex errors better!

**Comment by tksoh** [comment]
Tested and working. FYI, I still see the warning printed out on Application Output. Not sure it's necessary since we now have a dialog even though it doesn't hurt either.

**Comment by eteran** [comment]
Yea, the debug message happens in a common path, and I figure it has little to no harm so I didn't go out of my way to make it not print :-P
