### ISSUE TITLE
Implement the last few macros

### ISSUE THREAD

**Issue by eteran** [eteran/nedit-ng#282]
There's a handful of macros that went unimplemented for one reason or another. We should have them all implemented to a reasonable degree. Some may eventually be removed in future releases, but for 6.0... we want em all!

**Comment by eteran** [comment]
I **think**, that I've covered all macros which can be meaningfully implemented. Closing. If I've somehow missed one, then hopefully a user will report the oversight.

**Comment by grege2** [comment]
Hi Evan @eteran. Would you have a list of the new macros ? Apologies if I'm being lazy by not ferreting them out from the commit info. Cheers.

**Comment by eteran** [comment]
@grege2 so there shouldn't be anything really noteworthy, it really was just ones that are so infrequent in use that I hadn't gotten around to them yet. But I can come up with a list for you.
