### ISSUE TITLE
Typing is messed up

### ISSUE THREAD

**Issue by sambo57u** [eteran/nedit-ng#287]
Hi, between the changes of Jan 11 (works) and Jan 16 (problem) there is an issue that messes up typing on a line. When I type I end up getting spaces and blank characters pull characters previously typed. Hard to describe. I just wanted to put heading for
a data file I am preparing e.g.

Ecm     x_14      x_16      x_17      x_18      x_19

and typing was being messed up. I rebuild the Jan 11 git version and that works fine. This is Linux, Fedora 33, qt 5.15.2

**Comment by sambo57u** [comment]
I reversed the following changes from the latest git and it worked much better except when you typed in a letter the cursor would move one character ahead.
[reverse.patch.gz](https://github.com/eteran/nedit-ng/files/5826603/reverse.patch.gz)

**Comment by sambo57u** [comment]
To fix the extra blank character at the end I also had to reverse the more recent patch on QT<5.15.0. Removing those if statements solved that problem too. I am not sure what the root of the problem is. My font is DejaVu Sans Mono 11pt.

**Comment by tksoh** [comment]
I tried the latest version (2020.1-171-ga0ea7717) on Linux mInt 19.3 using your font, but did not see the problem you saw.

![2021-01-18 09_12_20-toshiba (tksoh-Satellite-L645_1 (tksoh)) - VNC Viewer](https://user-images.githubusercontent.com/494222/104862825-1d22e480-596f-11eb-8939-5c2b844ee2d4.jpg)

Some requests to help troubleshoot:
- Can you provide some screenshot? 
- what happen if you change to other fonts like courier new?
- can you provide a small sample of your file so we can test it out?

Thanks.

**Comment by tksoh** [comment]
BTW, I am using Qt 5.9.5

**Comment by eteran** [comment]
@sambo57u Do you happen to be on macOS? @anjohnson is experiencing a similar issue on macOS that I'm not seeing on linux or windows.

What that patch deals with is the unfortunate fact that some fonts are wider when bold, so it attempts to draw them all using a very ridged fixed size, once character at a time if necessary.

**Comment by eteran** [comment]
@sambo57u Regarding the "QT<5.15.0" patch. Do you mean this one?

```
#if QT_VERSION < QT_VERSION_CHECK(5, 15, 0)
	font.setStyleStrategy(QFont::ForceIntegerMetrics);
#endif
```

in src/Font.cpp?

**Comment by tksoh** [comment]
> @sambo57u Do you happen to be on macOS? @anjohnson is experiencing a similar issue on macOS that I'm not seeing on linux or windows.

@eteran he did mention  "This is Linux, Fedora 33, qt 5.15.2"

**Comment by eteran** [comment]
@tksoh I missed that, thanks.

This is very confusing because I'm looking at DejaVu Sans Mono 11pt on my Linux laptop and it looks great, with no weird quirks. ( I am using Qt 5.15.2 like he is, but use KDE)

I did roll back the `QFont::ForceIntegerMetrics` patch since it's only deprecated and seeing that in Qt's own code they still do different work depending on if it's set, it seemed best to just surgically disable the warning. I wonder if that alone would help @sambo57u :-/

**Comment by sambo57u** [comment]
I am using KDE too, latest, and Nvidia propriety drivers on a high res screen. The answer to QT if statement above, yes, that is the one. I do have a laptop running the same software too and can build the latest git and try again later. As, I said, after I removed alll those git commits it worked just fone. Leaving in the QT if statement was better but the cursor looked like it was one character ahead of the last tped character.

**Comment by sambo57u** [comment]
OK. I have built the latest git with the QT version check removed by eteran. So, far it works fine on my office computer and laptop both running the same software as my home machine where I saw the problem. I will check that also when I return home. By the way, I had a Ph.D. student whose names was Edgar Teran a few years ago who now works for a software company. First I thought eteran might be him!

**Comment by eteran** [comment]
Glad to hear that things seem better, please keep me posted regarding if it seems resolved. It's disappointing that Qt would deprecate a function without either making it have no effect OR at least saying "use X instead".

Also, it's pretty funny that you knew an Edgar Teran! It's pretty rare for me to even hear about Terans that I'm not related to (and all so far have been of Spanish descent, despite my family having no Spaniards that I'm aware of).

**Comment by sambo57u** [comment]
Yes, the home computer is also working now so the problem was that.

Yes, Edgar Teran was Spanish descent from Mexico!
