### ISSUE TITLE
incorrect macro comparison outcome

### ISSUE THREAD

**Issue by tksoh** [eteran/nedit-ng#292]
Using commit 455817323effad87929996262b6d0800cdfd6eda. Affects Windows 10 and Linux.

Run the following macro, NG says "" equals to 2:

> if ("" == 2)
>     dialog("same")
> else
>     dialog("not same")

![2021-01-22 17_11_43-Macro Commands](https://user-images.githubusercontent.com/494222/105470782-f3522080-5cd4-11eb-9d89-2278b9aa578a.jpg)

On a related topic. Somehow this would also crash Windows debug build with MSVC 2017. No issue with release build. Linux debug & release builds are not crashing either.

![2021-01-22 17_00_21-Untitled](https://user-images.githubusercontent.com/494222/105470313-5d1dfa80-5cd4-11eb-9831-924f0fa58239.jpg)

**Comment by eteran** [comment]
Oh, good find, i"ll investigate.

I believe the crash is Microsoft's STL debugging capabilities. So it's really a failed assertion. The assertion doesn't exist in gcc, and is "lucky" that the invalid access doesn't crash.

BTW, your bug reports have been REALLY helpful. Thanks for providing great detail on how to reproduce and the screenshots are great!

**Comment by eteran** [comment]
Should be fixed in master now!

**Comment by tksoh** [comment]
Thanks. Just thinking out loud, perhaps the macro engine requires some kind of test suite.

**Comment by eteran** [comment]
It probably should. The tough part is having a means to either drive a real NG instance or mock an instance enough to have good results.

But at the very least, we could have some tests that validate purely computational things!
