### ISSUE TITLE
text is statistic line off center vertically on linux

### ISSUE THREAD

**Issue by tksoh** [eteran/nedit-ng#295]
Running commit 9e9acf13b028d86a5a9951b3534a5a71bcad6d7c

This is a really minor cosmetic issue. Somehow on Linux the text are off center, leaving about twice a empty space below the text line compare to the space above the line. They look okay on Windows 10.

![2021-01-26 13_45_12-toshiba (tksoh's X desktop (tksoh-Satellite-L645_1)) - VNC Viewer](https://user-images.githubusercontent.com/494222/105805627-5c8ba980-5fdd-11eb-8178-2209ee58b059.jpg)

**Comment by pwhitbread** [comment]
Can I also add that the lack of padding on the left and right margins is a bit ungainly? i.e. in the above screenshot, where the / touches the left edge and the 0 touches the right edge.

**Comment by eteran** [comment]
The left/right padding should be pretty easy to tweak :-)

**Comment by eteran** [comment]
Should have a fix for this soon, sorry for the long delay.

**Comment by tksoh** [comment]
Just tried the latest commit. Unfortunately the vertical position is still off center.

**Comment by eteran** [comment]
@tksoh right, i haven't had a chance to do the minor fix for this (work has been super busy!), but I'll try to get one in soon!

**Comment by tksoh** [comment]
Oh, I misread your reply. Take your time.

**Comment by eteran** [comment]
Sorry that things took so long!! Just been SO busy lately. Just did a commit in master that does two things:

1. adds a little padding to the left and right of the status bar.
2. tightens up the vertical borders around the status widget. Interestingly, the text is actually vertically in the label widget... but the label itself is in a layout that has some padding around it. So I've tightened that up to help make things (hopefully) appear more vertically centered. Unfortunately, this may be a bit theme-sensitive. For me, things looked fairly vertically centered, even before this change in KDE's default widget theme.

Please let me know if this helps address the problem!

**Comment by eteran** [comment]
@tksoh out of curiosity, does the latest in master help the look on your end?

**Comment by tksoh** [comment]
It looks centered now (the nedit-ng window at the top). Also, the font size is a little larger. Not sure it's been changed in the code somehow, but I personally like it better than the old font size.

![2021-06-03 13_19_18-toshiba (tksoh's X desktop (tksoh-Satellite-L645_1)) - VNC Viewer](https://user-images.githubusercontent.com/494222/120591321-89aa0600-c46e-11eb-9628-1e81a06a4207.jpg)

**Comment by eteran** [comment]
Interesting about the font, it certainly wasn't intentionally adjusted, but if it looks better... I'll take it!
