### ISSUE TITLE
crash when closing tab while macro is running

### ISSUE THREAD

**Issue by marilmanen** [eteran/nedit-ng#306]
I accidentally closed a tab from which I had launched an xterm in a macro, so the macro was still running. Closing the tab caused a crash with nedit version 079cc39. Here is the terminal output with QT 5.15.3
Warning: QProcess: Destroyed while process ("/bin/tcsh") is still running.
Segmentation fault (core dumped)

**Comment by eteran** [comment]
Ouch, so so when you say "launched an xterm in a macro", what precisely do you mean, I don't recall macros themselves being able to start sub-processes.

Do you mean that you had it run a shell command?

**Comment by eteran** [comment]
Ohh... NVM. did you do an `execute_command` inside a macro? And that command was `xterm`?

**Comment by eteran** [comment]
Hmm, OK here's the steps I think I need to reproduce:

1. create a macro that simply says: 

```
execute_command("xterm")
```

2. Open multiple tabls

3. Run the new macro

4. Close the tab which ran the macro

---

Unfortunately, doing that, I **don't** get a crash. I do get a warning about `QProcess` being destroyed while still running, but no segfault. I'll continue to investigate.

**Comment by eteran** [comment]
OK, got a crash. Debugging :-)

**Comment by eteran** [comment]
Should be fixed in master! :-)

Thanks as usual!
