### ISSUE TITLE
nedit-ng crashes when using find

### ISSUE THREAD

**Issue by jim-nkt** [eteran/nedit-ng#32]
adding a patch in separate comment.
needed to remove the  "n" check from Search::HistoryByIndex
this was always causing null pointer by the second iteration.
+++++++++++++++
First thanks for porting this. I am a long time user. Built the original on solaris, HPUX, Irix, and linux back in the late 90's.
Recently while cutting and pasting a url form nedit to firefox (59) I found the cut and paste to firefox no longer works. I can cut and paste to anything else except firefox. Not sure why? So this prompted me to try your Qt version. Voila I can cut and paste again. Not sure what firefox did that makes it incompatible with the old nedit. The old nedit works fine with any version of firefox prior to version 59.  
I ran into some runtime problems with nedit-ng. I haven't worked in cpp code in a long time so pretty rusty.

platform OpenSuse leap 42.3
compiled using:
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER="/usr/bin/g++-5" ..

App starts up fine. 
I get a core dump due to the Q_ASSERT(entry) at line 717 of Search.cpp
If I switch to Q_CHECK_PTR(entry); 
I get the following error:

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

If I change the code to 
HistoryEntry *entry = HistoryByIndex(1);

then nedit-ng seems to work as expected (it doesn't crash, search history is available during session).

-- Jim

**Comment by jim-nkt** [comment]
diff --git a/source/Search.cpp b/source/Search.cpp
index 2210c38..0bc8774 100644
--- a/source/Search.cpp
+++ b/source/Search.cpp
@@ -775,16 +775,11 @@ int Search::historyIndex(int nCycles) {
  */
 auto Search::HistoryByIndex(int index) -> HistoryEntry * {
 
-    if (NHist < 1) {
+    if (NHist < 1 || index < 0) {
         return nullptr;
     }
 
-    const int n = historyIndex(index);
-    if (n == -1) {
-        return nullptr;
-    }
-
-    return &SearchReplaceHistory[n];
+    return &SearchReplaceHistory[index];
 }

**Comment by eteran** [comment]
Thanks, I'll apply this (or a variant of it) after i return from some travel tomorrow!

**Comment by jim-nkt** [comment]
Thanks Evan,
I will pull the latest. I am not the best C coder and a complete novice at Qt but I can probably help test down the road if you need testers.
-- Jim
