### ISSUE TITLE
Quick search: implement Clear&Paste by single click of middle mouse button

### ISSUE THREAD

**Issue by GrAndAG** [eteran/nedit-ng#340]
I missed the feature that I use a lot and which exists in classic nedit, but was not migrated to NG. I'm talking about the _clear button_ which is located on the right side of quick search entry.
![image](https://user-images.githubusercontent.com/18005116/219645113-e9b3db28-8895-4be5-a98f-5daf41ba6c93.png)
In classic nedit I can click this button by middle mouse button and this allows me to clear the search text and paste a new one from selection (aka mouse clipboard) in single action. This operation (to select and paste by MMB) is very common in Linux. 
In NG I have to do the same thing in 2 clicks instead - LMB on clear button and then MMB on search entry.
So, I've added the code below into `MainWindow.cpp` to re-implement the same behavior.

```
void MainWindow::setupISearchBar() {

        ui.editIFind->findChild<QToolButton *>()->installEventFilter(this);
// ...
} 

bool MainWindow::eventFilter(QObject *object, QEvent *ev) {

    if (ev->type() == QEvent::MouseButtonRelease && static_cast<QMouseEvent*>(ev)->button() == Qt::MiddleButton
        && object == ui.editIFind->findChild<QToolButton *>()) {
            ui.editIFind->setText(QApplication::clipboard()->text(QClipboard::Selection));
            return true;
    }
// ....
}
```

**Comment by eteran** [comment]
OK, I see. So while it should have the Qt built-in clear button, you want to be able to **replace** the text by middle clicking the button. Interesting. I use middle mouse click to paste all the time, but never considered middle mouse clicking the clear button!

I'll take a look at getting this in ASAP (not at my dev box at the moment).

**Comment by eteran** [comment]
merged into the master branch, thanks! Your code was pretty much able to be copy and pasted in :-)
