### ISSUE TITLE
nc-ng does not open the file while nedit-ng does (through an ssh connection).

### ISSUE THREAD

**Issue by ericxuo** [eteran/nedit-ng#350]
Hi,

I'm not sure this is an nedit-ng issue but since a few weeks (after I've upgrading from Mageia8 to Mageia9 and using commit version  450ad1733b74829c5cddd70999611e5b2c11565b), I can't open any file using nc-ng.
What I do : 
1) ssh remote
2) su -l root
3) nc-ng file
=> the file does not open, no error message
4) nedit-ng file
=> the file opens.

If I try to open a file without the "su 'l root" command, I don't have any issue. Has the root account some restrictions using nc-ng ?

Do you have any idea about this issue ? This was working fine till a few weeks ago.

Regards.

Xuo.

**Comment by ericxuo** [comment]
Hi,

After I've created another account, nc-ng works fine. It looks it comes from the root account.
After I've removed the directory .config/nedit-ng, I get the same issue. So it really seems to come from some root permissions.

Xuo.

**Comment by ericxuo** [comment]
Hi,

I think I've found the issue. I was coming from the fact that the user "root" had already an nc-ng session open locally on the remote station. Then the new nc-ng command was trying to open the file on the remote host itself but not through the ssh connection. After I've killed the local session of nc-ng, it is working fine.

Regards.

Xuo.

**Comment by eteran** [comment]
Nice! glad to hear it
