### ISSUE TITLE
Using the -geometry command parameter makes nedit-ng to fail opening a file.

### ISSUE THREAD

**Issue by ericxuo** [eteran/nedit-ng#38]
Hi,

The command I run : 
nc-ng -geometry +100+100 .tcshrc

What I get : 
![capture d ecran_2018-04-12_22-15-58](https://user-images.githubusercontent.com/9089499/38701790-23398d58-3e9f-11e8-98f4-c701acdabe4a.png)

There is no problem without the -geometry option.

This option can be run on the command line : 
/home/eric 106 # nc-ng -help
Usage:  nc [-read] [-create]
           [-line n | +n] [-do command] [-lm languagemode]
           [-svrname name] [-svrcmd command]
           [-ask] [-noask] [-timeout seconds]
           [-geometry geometry | -g geometry] [-icon | -iconic]
           [-tabbed] [-untabbed] [-group] [-wait]
           [-V | -version] [-h|-help]
           [--] [file...]

Any idea ?

Regards.

Xuo.

**Comment by eteran** [comment]
Interesting, it seems that this flag is not being parsed correclty by nc-ng

**Comment by eteran** [comment]
Same issue with `-lm` :-/

**Comment by eteran** [comment]
So, an observation made while fixing this.

Does this work in traditional nedit?

I've been able to fix the issue so it no longer errors and my fix also addresses what was going wrong with the `-lm` parameter. However, I haven't been able to get either nedit or nedit-ng to respect the geometry specified using the client/server mode.

**Comment by eteran** [comment]
Nevermind, geometry works, I was mistaking your specification for width/height, but it is, in fact, an x/y screen offset

**Comment by ericxuo** [comment]
Hi,

I've always used this parameter when I was using the native nedit. It is still in my alias, this is the reason why I was using it with nedit-ng (without remembering I was ...).
Thank you for the fix.

Regards.

Xuo.
