### ISSUE TITLE
Shell macros do not work

### ISSUE THREAD

**Issue by ericxuo** [eteran/nedit-ng#39]
Hi,

When running the Shell -> sort command, all the contents of the file are removed.
Same thing for Shell -> wc.
Shell -> expand makes nedit-ng to crash (the window disappears without any error message in the console). I don't know what Shell -> expand is supposed to do, but I don't think to close the window.

Shell -> Filter selection -> sort works.

Regards.

Xuo.

**Comment by eteran** [comment]
Interesting... historically I use shell -> sort pretty often, but I'll double check this and get a fix out as soon as I can reproduce this and diagnose the issue.

**Comment by eteran** [comment]
Interesting, reproduced in master branch but it worked in the past... Looking into it

**Comment by eteran** [comment]
Should be fixed!

**Comment by ericxuo** [comment]
Hi,

That's great. I'll update and test tomorrow.

Regards.

Xuo.

**Comment by ericxuo** [comment]
Hi,

It is working fine now. Thank you.

Regards.

Xuo.
