### ISSUE TITLE
Some words can't be translated.

### ISSUE THREAD

**Issue by ericxuo** [eteran/nedit-ng#41]
Hi,

I have attached the picture of something I don't understand.

![capture d ecran_2018-05-15_20-52-49](https://user-images.githubusercontent.com/9089499/40077453-ffead922-5881-11e8-92da-bc7b392d2b9a.png)

I don't see where the 'cancel' word has not been translated. I wonder if in the file DocumentWidget.cpp, the lines : 
`msgbox.addButton(QMessageBox::Cancel);`
shouldn't be replaced by : 
`msgbox.addButton(tr(QMessageBox::Cancel));`
or something like that.

Regards.

Xuo.

**Comment by eteran** [comment]
So, the `tr` suggestion is not how things work. `tr` is exclusively for marking string literals for translation, not numeric constants/enums such as `QMessageBox::Cancel`.

It is my understanding that these standard buttons are supposed to be automatically translated (part of the main benefit of having standard buttons!

Can you show me exactly how you are running nedit-ng to test the translations? Also, is it possible that you don't have the french locale built for your Qt installation?

**Comment by ericxuo** [comment]
Hi,

Here is what I do (as everybody else I guess) : 
cd \<where my nedit-ng git tree is located\>
git pull
rm -rf build
mkdir build
cd build
cmake ..
make

All my menus are now in french. When you've added my last changes, I could see them. 
It means that there is another place where this 'cancel' pattern has not been translated, but I really don't know where it is.
I'll have another look tomorrow.

Regards.

Xuo.

**Comment by eteran** [comment]
Any update on this, I think when using the default buttons that this is out of my control 😕. But I would expect that if you have the French translation files installed for Qt itself, that it should "just work"

**Comment by ericxuo** [comment]
Hi,

I don't know if I have the French translation files installed for Qt. I've asked how to check this but I didn't get any answer. I think so as my complete Mageia version is in french, but it is possible there are some files which are not.
As this is not a killer bug, I don't work on it at the moment. But I still see the 'Cancel' button each time I leave nedit-ng for example.

Regards.

Xuo.

**Comment by ericxuo** [comment]
Hi,

I've just noticed a few days ago that I didn't have this issue. I didn't update nedit-ng, so I guess some qt files on my Mageia6 OS have been updated .

Regards.

Xuo.
