### ISSUE TITLE
Zooming

### ISSUE THREAD

**Issue by mmorandi** [eteran/nedit-ng#46]
I think it would be great if it was possible to zoom in/out like in browsers, regardless of the character size.
Bonus point to be able to revert to the default scale factor with a shortcut.

**Comment by eteran** [comment]
Would a Ctrl + + and a Ctrl + - set if shortcuts 2 easily increase or decrease the font size be what you have in mind?

Or are you thinking something like Ctrl + mouse wheel?

**Comment by mmorandi** [comment]
Either one or the other would be perfectly fine (or even both like in firefox, if possible at all).

**Comment by eteran** [comment]
I'll look into how to best work this in! I was actually thinking about adding something like this just this morning.

**Comment by eteran** [comment]
Latest push now includes zooming via Ctrl+Scroll Wheel  :+1:
