### ISSUE TITLE
The contents of the windows shift on the right when selected.

### ISSUE THREAD

**Issue by ericxuo** [eteran/nedit-ng#53]
Hi,

Here is a behaviour which is new (or I didn't noticed it but I don't think so).
When I select some text in the nedit-ng window and my mouse goes on the left, then the window's contents shift of the right.
Then, it's a nightmare to get the original window's view.
I don't know where that behaviour comes from , nedit-ng or Qt, but this is (from my point of view) really boring.
Is there a way to prevent that behaviour ?
Bad behaviour : 

![screenshot_bad](https://user-images.githubusercontent.com/9089499/44281745-0eddb500-a259-11e8-813c-3043458d037e.png)

Good behaviour : 

![screenshot_good](https://user-images.githubusercontent.com/9089499/44281533-67f91900-a258-11e8-86e6-ab047ba02e3d.png)

Regards.

xuo.

**Comment by eteran** [comment]
I had reworked some scrolling stuff a couple of days ago and noticed that I introduced this bug. I **think** it is fixed in master, please let me know (assuming your other build issue is resolved)

**Comment by eteran** [comment]
Now that your build is fixed, can you confirm that this issue is resolved?
