### ISSUE TITLE
Error when compiling nedit-ng (missing file nedit-ng_fr.qm)

### ISSUE THREAD

**Issue by ericxuo** [eteran/nedit-ng#54]
Hi,

 I get an error while compiling the very last version of nedit-ng : 

Generating qrc source nedit-ng_automoc.dir/qrc_translations_OX5LPOHFSWODBI.cpp
RCC: Error in '/automount/Softs/local/nedit-ng/build/source/translations.qrc': Cannot find file 'nedit-ng_fr.qm'
AUTORCC: error: process for nedit-ng_automoc.dir/qrc_translations_OX5LPOHFSWODBI.cpp failed:

Do you know where it could come from ? Two days ago, I could compile everything correctly.

Regards.

Xuo.

**Comment by eteran** [comment]
Hmm, we did JUST update the French translation, buy it seems to compile correctly locally for me. Have you tried a completely fresh build directory?

I'll do the same with the latest in master and try to get to the bottom of this.

**Comment by ericxuo** [comment]
Hi,

I've just compiled from scratch and I've got the same error.
nedit-ng_fr.qm is not part of the git clone. Is it build on the fly during cmake or make ?

Regards.

Xuo.

**Comment by eteran** [comment]
It is built on the fly.

**Comment by ericxuo** [comment]
Hi,

I have this kind ofwarnings during the make command : 
make[2]: Avertissement : le fichier « Regex/CMakeFiles/Regex.dir/depend.make » a une date de modification 62 s dans le futur
Translation : Warning : the file « Regex/CMakeFiles/Regex.dir/depend.make » has a modification date 62s in the future.

Could this explain the error on nedit-ng_fr.qm ?
Is there a log I could have a look at to see if I can get more explanations about the reason why this file is not created ?

Regards.

Xuo.

**Comment by eteran** [comment]
That sounds like you aren't using a fresh build directory if it thinks that some files were modified in the future.

Try the following please:

    rm -rf /automount/Softs/local/nedit-ng/build/
    mkdir /automount/Softs/local/nedit-ng/build/
    cd /automount/Softs/local/nedit-ng/build/
    cmake ..
    make

There should be a set of lines similar to this one at some point:

```
Scanning dependencies of target nedit-ng_autogen
[ 22%] Generating nedit-ng_fr.qm
Updating '/home/eteran/projects/nedit-ng/build/source/nedit-ng_fr.qm'...
    Generated 921 translation(s) (921 finished and 0 unfinished)
    Ignored 2 untranslated source text(s)
```

**Comment by ericxuo** [comment]
Hi,

Using the nedit-ng.zip file (instead of the git clone command), I don't have the "modification in the future" issue BUT I still have the Cannot find file 'nedit-ng_fr.qm' one.

Regards.

Xuo.

**Comment by ericxuo** [comment]
Hi again,

The problem does not come the .zip file or the git command but from a local directory (/home/... where I don't have any "modification in the future" issue) and from an auto-mounted one (where I get this issue).
Now, we just have to understand the reason why I get the "Cannot find file 'nedit-ng_fr.qm'" issue.

Xuo.

**Comment by eteran** [comment]
Is your clock correct? You definitely shouldn't be getting warnings about files being modified in the future. I think that is something which tends to mess with `make`

**Comment by eteran** [comment]
is auto-mounted some remote filesystem? could it possibly be an issue with that filesystem? Can you try building it in a local filesystem?

**Comment by eteran** [comment]
> I don't see any lines with nedit-ng_autogen.
> I can't go further than 16% for the make command.
> Are you sure /home/eteran/projects/nedit-ng is the same as https://github.com/eteran/nedit-ng.git ?

Yes, I just did a fresh checkout and it built correctly on my machine :-/

**Comment by ericxuo** [comment]
Hi,

My last "makes" (with either the zip file or a git clone command ) have been done locally, without any clock issue. But it does not compile correctly in both cases.

Regards.

Xuo.

**Comment by eteran** [comment]
I honestly have no idea :-/

it builds locally for me and on my travis CI instance:

https://travis-ci.org/eteran/nedit-ng/jobs/417422305

Which if you look at the log, Generating nedit-ng_fr.qm is one of the very first things it does.

**Comment by eteran** [comment]
I can't think of anything that should make a difference ... The build doesn't (well shouldn't) care what locale you're currently running.

**Comment by ericxuo** [comment]
Hi,

My locale : 
/automount/Softs/local/nedit-ng/build 491 # locale
LANG=fr_FR.UTF-8
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=

And in my compilation, I have : 
[ 15%] Built target Util
Scanning dependencies of target nedit-ng_automoc

while you have several other targets I don't have :

[ 16%] Built target Util
Scanning dependencies of target Settings
[ 16%] [BISON][parser] Building parser with bison 3.0.2
[ 17%] Building CXX object Settings/CMakeFiles/Settings.dir/Settings.cpp.o
Scanning dependencies of target Interpreter
[ 18%] Building CXX object Interpreter/CMakeFiles/Interpreter.dir/interpret.cpp.o
[ 19%] Linking CXX static library libSettings.a
[ 19%] Built target Settings
[ 20%] Building CXX object Interpreter/CMakeFiles/Interpreter.dir/parse.cpp.o
[ 21%] Building CXX object Interpreter/CMakeFiles/Interpreter.dir/parser.cpp.o
Scanning dependencies of target nedit-regex-test
[ 22%] Building CXX object Regex/test/CMakeFiles/nedit-regex-test.dir/Test.cpp.o
[ 23%] Linking CXX static library libInterpreter.a
[ 23%] Built target Interpreter
Scanning dependencies of target nedit-ng_autogen
...

And you don't have the target nedit-ng_automoc

Xuo.

**Comment by eteran** [comment]
cmake version?

**Comment by eteran** [comment]
What i meant was, what is your cmake version. `cmake --version`

**Comment by ericxuo** [comment]
cmake version 3.7.2

**Comment by eteran** [comment]
I've added a line I removed (which seems to do nothing) from the translations aspect of the cmake file.

Can you do a fresh clone and see if that makes a difference please?

**Comment by ericxuo** [comment]
hi,

No it was really an unuseful line. It didn't change anything.

Xuo.

**Comment by ericxuo** [comment]
Do you know how to git clone version 2018.7 of nedit-ng ?

Xuo.

**Comment by eteran** [comment]
I'm away from my computer, but there is a way to check out any tag. I'll let you know later tonight

**Comment by eteran** [comment]
git clone https://github.com/eteran/nedit-ng.git
    cd nedit-ng
    git checkout 2018.7
    # now you have the 2018.7 code checked out

If that works, I guess I'll just revert my tweaks to the build system, but honestly I don't understand why the old system would be any different since the translation system is the one part I **didn't change** since the last release.

**Comment by ericxuo** [comment]
Hi,

If I summarize what I did, the issue comes from the file source/CMakeLists.txt
I've cloned nedit-ng master repository and copied into its source directory the file CMakeLists.txt from the tag 2018.7 (which compiles correctly). And it works.
In other words, the only file I need to change for nedit-ng to compile on my side is the file source/CMakeLists.txt.

Regards.

Xuo.

**Comment by eteran** [comment]
Please let me know if the latest master builds for you. I don't know why the old version works and the new one does (they both use the same exact code for the translation stuff)... but it seems to make a difference.

**Comment by ericxuo** [comment]
Hi,

Yes, the last master builds for me.
You think the problem comes from the translation code ?

Regards.

Xuo.

**Comment by eteran** [comment]
Well, the issue you were having is in the generation of the `nedit-ng_fr.qm`, which is the binary version of the french translation file. For some reason, it wasn't being generated with the "improved" cmake file, but worked for me and travis-CI builds.

I have no idea what the cause was though. Oh well.

**Comment by ericxuo** [comment]
Hi,

Here is a "working" source/CMakeLists.txt.

Xuo.
[CMakeLists.txt](https://github.com/eteran/nedit-ng/files/2300494/CMakeLists.txt)

**Comment by eteran** [comment]
That looks like **exactly** the way it was when you said it wasn't working though

**Comment by ericxuo** [comment]
Hi,

Here are the differences : 
29a30,35
> list(APPEND QRC_FILES ${TRANSLATIONS_QRC})
> 
> qt5_add_resources(QRC_SOURCES
>       nedit.qrc
>       ${TRANSLATIONS_QRC}
> )
33c39
<       ${TRANSLATIONS_QRC}
---
>       ${QRC_SOURCES}

Xuo.

**Comment by eteran** [comment]
Interesting, I'll take a look. The build is currently working as it's supposed to, so I'm in no hurry. I'll reach out to you when I give the "new" method a go again (I prefer it because it's simpler to maintain AND it's a slightly faster build too).

**Comment by eteran** [comment]
@ericxuo I've pushed a commit using your version of the CMake file, when you get a chance, can you double check that it works as expected?

Thanks

**Comment by ericxuo** [comment]
Hi,

It could compile it without any problem.

Regards.

Xuo.
