### ISSUE TITLE
2018.8 build fails on older systems

### ISSUE THREAD

**Issue by luigino** [eteran/nedit-ng#56]
Trying to build nedit-ng 2018.8 on openSUSE Leap 42.3 and [this](https://github.com/eteran/nedit-ng/files/2339018/nedit-2018.8.txt) is what happens.

**Comment by eteran** [comment]
Oh no, looks like a resource file is included twice. I'll look into it and try to get a fix out today

**Comment by eteran** [comment]
should be fixed in 2018.9. Please reopen this bug if it is not.

**Comment by luigino** [comment]
Works for me :thumbsup:
