### ISSUE TITLE
make error in intepret.cpp in CentOS 7

### ISSUE THREAD

**Issue by snail3git** [eteran/nedit-ng#57]
I am building under Centos 7 and got syntax error in the make stage:

/home/mchienlocal/Downloads/nedit-ng-master/GSL/include/gsl/gsl_byte:105:1: error: expression \u2018(l = ((gsl::byte)(((unsigned char)l) | ((unsigned char)r))))\u2019 is not a constant-expression
 }

I have attached my make log file (Line 552), appreciate
[make_error.txt](https://github.com/eteran/nedit-ng/files/2355182/make_error.txt)
 if anyone can point out where I got wrong..

**Comment by eteran** [comment]
So, the GSL is an external library from Microsoft based on C++ standards.

Can you tell me what compiler version you are using?

**Comment by eteran** [comment]
Looks like CentOS 7 uses g++-4.8 as the default compiler, nedit-ng requires C++14 support, I believe that g++-5 should be sufficient.

This answer on SO, looks promising:

https://stackoverflow.com/a/39731134/13430

**Comment by snail3git** [comment]
Yes default g++4.8.5 in CentOS failed the C++14 checking in the cmake, I was using g++4.9.2 and it passed the C++14 check so I thought it was ok. Will give g++5 a try, thanks for the tip.

**Comment by snail3git** [comment]
g++6.3.1 passed the make stage without any warning/error, I can run the program now. I must say it looks much better/modern than nedit 5.7, thanks again for the quick help!

**Comment by eteran** [comment]
No problem, glad you got it working!
