### ISSUE TITLE
word selection - line selection  are lost when pointer is moving

### ISSUE THREAD

**Issue by patricevenant** [eteran/nedit-ng#60]
- When I double click on a word, this one is correctly selected, but if I move the pointer, the selection isn't extended word by word. In fact, not more selection.

- When I triple click on a line, the selection is correctly apply to the full line, but if I move the mouse, the selection mode is go back to character selection. I lost the line mode selection.

- Different behavior from the motif nedit is, we can't be able to start a selection when the pointer is above the line number area. This is not so easy.

**Comment by eteran** [comment]
Wow, good finds. Those are very subtle differences.

The first and second ones will need some looking into. For the line number one, I know the cause, (Completely different implementation of line numbers to take advantage of some things that Qt can do and simplify general logic), so I'll look into the best way to reproduce the behavior.

**Comment by eteran** [comment]
Let me know if this works (and/or introduces any new bugs). The code was there to do it, but there were some quirks with the multi-click tracking I needed to iron out.

**Comment by patricevenant** [comment]
That's working so well, I'm impress of rapidity to fix. Many thanks
