### ISSUE TITLE
Open Selected issues

### ISSUE THREAD

**Issue by patricevenant** [eteran/nedit-ng#61]
I got the pop-up error "Could not open ... No such file or directory" when using the 'Open Selected' menu. The path shown by the dialog window isn't correct. It's the case when I select a full path name started by '/'. With the locally file name, (the file alone), the targeted path seems correct, but I got the error pop-up too.

nc-ng version 2018.12

Regards

**Comment by eteran** [comment]
So, the behavior is slightly different from classic nedit because I wanted to support multiple search paths. The path you see in the message is the **last** one it checked. Basically, the rules are that when you select:

```
#include <filename.h> // search standard include paths, /usr/include, /usr/local/include by default, configurable in config.ini
#include "filename.h" // search relative to this document's path
filename.h // search relative to this document's path
any path starting with a "/" // assume it is an absolute path
```

Can you describe the details of when this fails for you so that I can replicate the error and fix it?

(what are you selecting, which path do you expect it to be found in, what the error message says, etc...)

**Comment by patricevenant** [comment]
In fact, I've checked my config.ini (I think I use nedit-import to import my old nedit-rc, I'm not so sure as I made different try). Any way, I found this nedit.includePaths=@Invalid() in my current one. This could explain. So, I completely remove the config.ini to restart with a new default one. I can now play with 'Open selected'. My new config.ini have :
```sh
nedit.includePaths=/usr/include/, /usr/local/include/
```
Then, I'm able to open selected file. 

The only way which is not working, is when I select a filename from a terminal shell or any other place than the document itself. I take care to play with the 'Open selected' on the right opened document place. For example :
![capture readme-1](https://user-images.githubusercontent.com/43247771/45845830-34485d80-bcf4-11e8-93f0-e671b3483560.PNG)

![capture readme-2](https://user-images.githubusercontent.com/43247771/45845844-3ca09880-bcf4-11e8-8506-7d16032a07f3.PNG)

Hope this help

**Comment by eteran** [comment]
I believe it is fixed now, please confirm when you get a chance. Re-open if there are still issues.

**Comment by patricevenant** [comment]
Well done ! That's working now. Thanks!

**Comment by marilmanen** [comment]
ctrl+y does not yet work with absolute names when the file name starts with a dot

$ ls -1 /tmp/.foobar /tmp/foobar
/tmp/.foobar
/tmp/foobar

with the second file ctrl+y works fine, but with the first file I get 
Could not open /tmp/.foobar:
No such file or directory

source version used: e5d0bc8d

**Comment by eteran** [comment]
@marilmanen, I'll look into it!

**Comment by eteran** [comment]
@marilmanen should be fixed in the latest push, please reopen if the issue persists :)

**Comment by marilmanen** [comment]
Partly related issue: When selecting file name for "open selected" and accidentally including leading or trailing space characters, the open fails as space characters are considered as part of the actual file name. Could you add automatic removal of trailing and leading space characters for the selection?

**Comment by eteran** [comment]
@marilmanen

Yea, I can make that tweak
