### ISSUE TITLE
Tab bar improvements

### ISSUE THREAD

**Issue by anjohnson** [eteran/nedit-ng#62]
I just came across nedit-ng yesterday, I love it — as a long-time user of Nedit I thank you!

Here are some minor things I'm noticing about the tab bar, should you be looking for small jobs to do...

- Frankly it looks pretty ugly, and I don't mean the shape of the tabs; the bar is separated from the text pane by several pixels. If the blue line marking the currently active tab were drawn in the same color as the text background that might help a bit, or use the theme's colors and draw the active tab in the focused color and the others as unfocused?
- The close button box on the right-hand side isn't quite aligned with the tabs (it's 1 pixel too high, and hangs off the right-hand end of the bar). If it can't easily be aligned could you perhaps turn off the outline of the box?
- Any chance of reducing the height of the bar? It's taller than the menu bar, which is the reverse of Nedit on my system at least. That might be due to my font choices, but maybe it could use the same font as the menu bar does instead of using the theme's title-bar font?

I'm sure I'll have lots more observations and requests if you want them, but in any case I am grateful that Nedit will live on!

- Andrew

**Comment by eteran** [comment]
Glad you like it!

I'll definitely take a look at what I can do to smooth out these visual differences. Can you specify your platform, desktop, etc. Or even possibly provide some screen shots for reference?

Also, nedit-ng has a "hidden" feature we may be able to utilize to fix this! if a style.qss file is found in the config directory, it'll load Qt style sheets (they function like CSS) for the app! We may be able to get things looking perfect just by editing this file :-). We'll have to investigate and see.

**Comment by anjohnson** [comment]
Hi Evan,

RHEL 7.5 on x86_64, with I think Gnome 3.22.2 and Qt 5.9.2. I installed Red Hat's devtoolset-7 to get GCC 7.2.1 for the C++14 support.

Here's a snapshot, with a Nedit window on top for comparison:

![image](https://user-images.githubusercontent.com/5453863/45894165-37def180-bd93-11e8-82e9-ede472cb4771.png)

BTW your README's list of requirements is missing CMake 3.0 — RHEL 7.5 comes with CMake 2.18.12 which wasn't new enough to build nedit-ng.

- Andrew

**Comment by eteran** [comment]
README has been fixed, thanks!

I agree that doesn't look ideal. Especially the close button. I have been considering using Qt's built-in "close button per tab" as it would "just work" and look good by default.

but that would be larger change from nedit classic's look.

**Comment by anjohnson** [comment]
I don't know Qt so not sure if you could do this, but how about making the close button into a proper tab of its own that has Qt's "close button per tab" turned on to provide the button. That should at least match the visuals for the current theme properly, although whether you could do that and fit in all the right plumbing behind it to make it close the current tab instead of the one that the button belongs to I have no idea.

Thanks for considering this!

**Comment by eteran** [comment]
I definitely will see what I can do, it's a shame that it isn't quite right, because on KDE the corner widget looks **perfectly** aligned and has a nice look due to the flat theme.

![image](https://user-images.githubusercontent.com/571477/45896767-1e45a600-bda3-11e8-9495-42a1878947a9.png)

**Comment by anjohnson** [comment]
Your KDE version definitely looks much better; unfortunately I'm forced to use Gnome because KDE doesn't work properly with the system configurations here. The Gnome window manager seems to cause other minor problems as well, which I'll probably report as issues in due course...

BTW I've just replaced my build of the 2018.12 tarball release with a clone of the Github master, so I'll be happy to build and try out new versions on request (work-time permitting of course).

**Comment by eteran** [comment]
There is a new compile time option `PER_TAB_CLOSE`, that will use Qt's native tab close buttons (one per tab) instead of the single one in the corner.

I expect that this should improve the aesthetics a little at the cost of a change in behavior. Though that change may be generally considered an improvement as it is more conventional in modern applications.

**Comment by anjohnson** [comment]
:+1: Definitely looks better in my case.
I'm going to close this issue since the blue outline around the edit window has now gone, and the other point doesn't seem relevant any more.

Thanks!
