### ISSUE TITLE
Scroll bar calculations

### ISSUE THREAD

**Issue by anjohnson** [eteran/nedit-ng#63]
When editing a short document that doesn't fill the window vertically I would expect the scroll-bar to be the full height of the window, but it's only half the window height and I can even use the mouse-wheel to move it up and down, although the text doesn't move at all.

For a longer document the scrolling works as expected except that the height of the scroll-bar is wrong, and when scrolling to the end of the document the bar doesn't reach the bottom of the pane when the last line comes into view; at that point I can use the mouse wheel to continue moving the scroll-bar downwards without the text moving any further.

I suspect these are both symptoms of the same problem related to the scroll-bar calculations, maybe an off-by-one error in a divisor somewhere? A minor problem though, cosmetic.

- Andrew

**Comment by eteran** [comment]
I have noticed that as well. IIRC, it only happens when wrapping is enabled, I would like to get it "perfect" of course, but it hasn't been top of my list since it is indeed strictly cosmetic.

**Comment by anjohnson** [comment]
Ah, yes it only happens with Wrap = Continuous (which was the default default, although not my personal preference).

**Comment by eteran** [comment]
Yea, I don't use wrap either typically. I plan to make it default to non-wrapped at some point in the future as I feel it makes more sense for a code editor.

I believe that I know the cause of the issue, it has to do with the fact that in wrapped mode, the "number of lines" isn't quite as straightforward as counting newlines. Motif uses a different system for specifying the scrollbar parameters, and it seems that some of them aren't quite right when using the more complex stuff.

I'll try to get to the bottom of it eventually though!

**Comment by eteran** [comment]
I think this is fixed, (along with a fix for some parts of wrap mode). Please reopen if the problem persists or if scrolling is otherwise broken by this.

**Comment by anjohnson** [comment]
Looks fixed to me, thanks!
