### ISSUE TITLE
ctrl-y does not work with absolute file names

### ISSUE THREAD

**Issue by mrbald** [eteran/nedit-ng#64]
When I try to `ctrl-y` an absolute location `/home/bobah/...` it shows an error dialog "could not open `/home/bobah//home/bobah/...` ..."

**Comment by eteran** [comment]
I believe this is a dupe of issue #61 , which has been fixed in master. Please re-open if the issue is reproducible in the master branch.

**Comment by mrbald** [comment]
In the master build `ctrl-y` works correctly indeed. Thanks @eteran
