### ISSUE TITLE
Find Again action when switch between tab

### ISSUE THREAD

**Issue by patricevenant** [eteran/nedit-ng#66]
I got a behavior issue when I play with the "Incremental Search Line". The viewed text isn't updated following the selected string, the display is freeze. I just have to click on the viewed text to come back to a classic behavior, I mean the display follows the selected string in different places.

To reproduce that, I select a string on a file through incremented search line. Then I click on another tab for another file which contents the same string too. So from that, a Ctrl+G doesn't scroll the text to the right place. After a click in the middle of the displayed text (the cursor is updated), the scrolling is back again.

**Comment by eteran** [comment]
Let me see if I follow this issue correctly:

1. You open 2 documents
2. you use the incremental search
3. you switch tabs
4. You press Ctrl+G, it does not perform the search in the new tab correctly
5. clicking in the new tab's view corrects the issue

Is that right?

**Comment by patricevenant** [comment]
For the 4., the Ctrl+G perform correctly the search (I saw Statistics Line updated for each place), the display isn't updated.
For 5. yes just a click on the view of the text, (which update the cursor), from then, the display is updated correctly after each Ctrl+G.

**Comment by eteran** [comment]
Hmm, what version are you using?

**Comment by patricevenant** [comment]
2018.12

**Comment by eteran** [comment]
OK, interesting. Sounds like a viewport update is not being done for some reason. Things seem OK here, but I'll look through the code to see if I can identify what you're running into.

**Comment by eteran** [comment]
Ah, well, I should probably replicate that behavior anyway then :-)

**Comment by eteran** [comment]
I believe that the latest in master replicates the behavior in classic nedit now. Please reopen this issue if there is some aspect of it that I missed.
