### ISSUE TITLE
Incremental search doesn't open with my Default Search Style

### ISSUE THREAD

**Issue by anjohnson** [eteran/nedit-ng#67]
Another minor issue...

I have Default Search Style set to Regular Expression, but when I type CTRL+I none of the check-boxes are checked.

Supplemental issues:
+ The word "Case" butts up against the right edge of the window, it could use a small right-margin:
![image](https://user-images.githubusercontent.com/5453863/45979095-987c6180-c013-11e8-887f-5a30a968bd56.png)

+ Could we have something like a tool-tip to remind us whether the "Case" check-mark means sensitive or insensitive? Actually all 3 check-boxes could become graphic buttons if you can find suitable icons.

+ Clicking the "RegExp" check-box also sets "Case" the first time I do it on a newly-started process. Actually I currently have it in a state where clicking RegExp also toggles Case, but it hasn't always done that. Hmm, does it actually store a RegExp Case setting and a Non-RegExp Case setting? It looks like that's what it's doing, but the result was a bit confusing until I noticed that.

**Comment by eteran** [comment]
I just checked with classic nedit. This indeed is supposed to respect the default settings. I'll get a patch for that out ASAP.

**Comment by anjohnson** [comment]
The RegExp setting stores Case thing does not match classic Nedit AFAICS.

Thanks!

**Comment by anjohnson** [comment]
Hi Evan — yes, the original issue is fixed; when I bring up the incremental search box the check-boxes now match my default search settings. I like the new tool-tips too, they provide just enough of a reminder what having Case checked means.

As to the link between the RegExp and Case check-boxes I evidently never played around with them enough before, the two versions do behave the same. What I was trying to describe is that the setting for Case is remembered separately when RegExp is checked and when it's unchecked, so changing RegExp will also change Case if those two remembered settings for Case are different.

Thanks, as far as I'm concerned this issue can be closed now.

**Comment by eteran** [comment]
BTW, I have a trivial fix for the case checkbox alignment :-).

You can just use the hidden styling feature! Create a file named:

`$HOME/.config/nedit-ng/style.qss`

and put this in it:

```
#incrementalSearchFrame {
	margin-right: 20px
}
```

**Comment by anjohnson** [comment]
@eteran Do you realize that you opened a secret door there...  :smiley:
