### ISSUE TITLE
Window from a newly-detached tab can't be File→Closed

### ISSUE THREAD

**Issue by anjohnson** [eteran/nedit-ng#71]
File⇒New, Right-click on the new tab, Detach tab. The new window has File⇒Close grayed out and Ctrl+W disabled, although the window-manager's Close button does properly close the window. At some point later these controls do get enabled but I'm not sure exactly what triggers that.

**Comment by eteran** [comment]
I'll take a look!

**Comment by eteran** [comment]
Should be fixed in the latest master!
