### ISSUE TITLE
Truncate long filenames in tabs?

### ISSUE THREAD

**Issue by anjohnson** [eteran/nedit-ng#74]
Hi Evan,

I work with code that has some longish filenames (and I don't mean paths, the files themselves have names in the 30+ character range). When I have a couple of those files open in tabs the tab bar loses its usability, for example:
![image](https://user-images.githubusercontent.com/5453863/47443938-0040dc00-d77b-11e8-9793-417927bcb715.png)
The scroll buttons on the tab-tar are not the best interface when there are lots of files open, and the mouse-wheel switches tabs instead of just scrolling the tab-bar.

It doesn't help that the font used for window decorations is wider than the Motif one. Here are the same pair of files open in the original nedit — their names are already clipped, but I don't mind that:
![image](https://user-images.githubusercontent.com/5453863/47444152-780f0680-d77b-11e8-929c-b5e9d5955c66.png)

When there are lots of files open, nedit even shortens the tabs to maximize the number visible:
![image](https://user-images.githubusercontent.com/5453863/47444361-ebb11380-d77b-11e8-86db-c5a4e7f5586d.png)
Note that all the tabs are the same width, which is different to how Qt shows them.

I guess I can switch to using the Windows menu to find specific tabs, but it would be nice if you could clip the filenames shown in the tabs somehow. Maybe try replacing the middle characters with an elipsis … but that would only work down to a certain size. Unfortunately the 'save needed' indicator takes up a lot of tab space too, and it would be nice to be able to replace that with a trailing `*` or `(*)`.

This would also be another great place for a tool-tip, so hovering over a tab with a truncated name would show the full filename.

Thanks for listening!

**Comment by eteran** [comment]
should be doable, at the very least, I can make it an option to elide long filenames in tabs

**Comment by eteran** [comment]
OK, I have a solution for you pushed to master.

There is a new "advanced setting" (not in the UI) called: `nedit.truncateLongNamesInTabs`

* Setting this to zero (the default) will perform no truncation
* Setting this to a positive integer will limit the tab string to that number (minus 3 for the "..."), and elide the text to the right (the END of the string is kept).
* Setting this to a negative integer will limit the tab string to that number (minus 3 for the "..."), and elide the text to the left (the START of the string is kept).
