### ISSUE TITLE
Double-click in dialog to Move Document?

### ISSUE THREAD

**Issue by anjohnson** [eteran/nedit-ng#76]
Hi Evan,

This may be a quick one to implement: I'm pretty sure that in nedit when the Move Document dialog was open, I could double-click on a window title in the list to move the selected tab there without having to Select the window title and click the Move button.

- Andrew

**Comment by eteran** [comment]
You are correct that nedit classic allowed a double click here. I'll get it in there :-)

**Comment by anjohnson** [comment]
:+1: Thanks!
