### ISSUE TITLE
nedit-ng SIGPIPE, Broken pipe

### ISSUE THREAD

**Issue by patricevenant** [eteran/nedit-ng#79]
Hi,
I got again the strange behavior as the nedit-ng/nc-ng is break, all attached windows are killed. This time I try to see what gdb could say about this situation. This happens when I double click on the Open Dialog File. Below is what I saw in the debugger. Hope this will help.

(gdb) attach 5329
Attaching to process 5329
[New LWP 5330]
[New LWP 5331]
[New LWP 5332]
[New LWP 5333]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007f1ab7910bf9 in __GI___poll (fds=0x55fb13752890, nfds=3, timeout=10378) at ../sysdeps/unix/sysv/linux/poll.c:29
29	../sysdeps/unix/sysv/linux/poll.c: No such file or directory.
(gdb) cont
Continuing.
[New Thread 0x7f1a93fff700 (LWP 12459)]
[Thread 0x7f1a93fff700 (LWP 12459) exited]

Thread 1 "nedit-ng" received signal SIGPIPE, Broken pipe.
0x00007f1ab790c187 in __GI___libc_write (fd=2, buf=0x7ffdc72aa530, nbytes=158) at ../sysdeps/unix/sysv/linux/write.c:27
27	../sysdeps/unix/sysv/linux/write.c: No such file or directory.
(gdb) info stack
#0  0x00007f1ab790c187 in __GI___libc_write (fd=2, buf=0x7ffdc72aa530, nbytes=158) at ../sysdeps/unix/sysv/linux/write.c:27
#1  0x00007f1ab78871bd in _IO_new_file_write (f=0x7f1ab7be8680 <_IO_2_1_stderr_>, data=0x7ffdc72aa530, n=158) at fileops.c:1203
#2  0x00007f1ab7887b2f in new_do_write (to_do=<optimized out>, 
    data=0x7ffdc72aa530 "Warning: QXcbConnection: XCB error: 3 (BadWindow), sequence: 60951, resource id: 25276336, major code: 40 (TranslateCoords), minor code: 0 ((null):0, (null))\n", fp=0x7f1ab7be8680 <_IO_2_1_stderr_>) at fileops.c:457
#3  _IO_new_file_xsputn (f=0x7f1ab7be8680 <_IO_2_1_stderr_>, data=<optimized out>, n=158) at fileops.c:1277
#4  0x00007f1ab785a707 in buffered_vfprintf (s=s@entry=0x7f1ab7be8680 <_IO_2_1_stderr_>, 
    format=format@entry=0x55fb1194c557 "Warning: %s (%s:%u, %s)\n", args=args@entry=0x7ffdc72acaf0) at vfprintf.c:2350
#5  0x00007f1ab7857726 in _IO_vfprintf_internal (s=0x7f1ab7be8680 <_IO_2_1_stderr_>, 
    format=0x55fb1194c557 "Warning: %s (%s:%u, %s)\n", ap=ap@entry=0x7ffdc72acaf0) at vfprintf.c:1301
#6  0x00007f1ab7860e54 in __fprintf (stream=<optimized out>, format=<optimized out>) at fprintf.c:32
#7  0x000055fb11851124 in (anonymous namespace)::messageHandler (type=QtWarningMsg, context=..., msg=...)
    at /Projects/Tools/NEdit/nedit-ng/src/nedit.cpp:35
#8  0x00007f1ab85c1467 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007f1ab85c228e in QMessageLogger::warning(char const*, ...) const () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007f1ab18da2a9 in QXcbConnection::handleXcbError(xcb_generic_error_t*) () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#11 0x00007f1ab18de58b in QXcbConnection::processXcbEvents() () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#12 0x00007f1ab87e6122 in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007f1ab953482c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007f1ab953c0f4 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007f1ab87b69a8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00007f1ab87b911d in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007f1ab88102c3 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x00007f1ab5d2d387 in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007f1ab5d2d5c0 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007f1ab5d2d64c in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#21 0x00007f1ab880f8ef in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007f1ab87b49ea in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x00007f1ab87bda84 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#24 0x000055fb11851a33 in main (argc=2, argv=0x7ffdc72ad5c8) at /Projects/Tools/NEdit/nedit-ng/src/nedit.cpp:124
(gdb)
#7  0x000055fb11851124 in (anonymous namespace)::messageHandler (type=QtWarningMsg, context=..., msg=...)
    at /Projects/Tools/NEdit/nedit-ng/src/nedit.cpp:35
35			fprintf(stderr, "Warning: %s (%s:%u, %s)\n", qPrintable(msg), context.file, context.line, context.function);
(gdb) p stderr
$1 = (_IO_FILE *) 0x7f1ab7be8680 <_IO_2_1_stderr_>
(gdb) p context.function
$2 = 0x0
(gdb) p context.line
$3 = 0
(gdb) p context.file
$4 = 0x0
(gdb) p msg
$5 = (const QString &) @0x7ffdc72acc98: {static null = {<No data fields>}, d = 0x55fb13d2fa10}
(gdb)

**Comment by eteran** [comment]
Hmm, this still look like a possible issue with the Qt installation on your system. The only nedit-ng code in that call stack that I can see is the attempt to print the message :-/.

**Comment by patricevenant** [comment]
Yes, It seems Qt is not so stable on my Ubuntu :( I change the settings to avoid the qt5ct which cause problem on my side. So I put QT_QPA_PLATFORMTHEME=gtk3 for a couple of days now, I haven't any more my crash.

**Comment by eteran** [comment]
Thanks for the follow up
