### ISSUE TITLE
Moving a tab with unsaved edits (minor, cosmetic)

### ISSUE THREAD

**Issue by anjohnson** [eteran/nedit-ng#81]
If I start editing a file in one window and (without saving) either detach the tab or move it to another window, the "unsaved" status indicator from the old tab doesn't appear in the new window. The "(*)" in the title bar is correct though. It hasn't saved the file, and Ctrl-Z Shift-Ctrl-Z restores the indicator properly.

**Comment by eteran** [comment]
Good catch. I'll get a fix for that ASAP!

**Comment by eteran** [comment]
Should be fixed!
