### ISSUE TITLE
Installation instructions for Windows OS

### ISSUE THREAD

**Issue by DougRzz** [eteran/nedit-ng#82]
Hi, I used to be a big fan of Nedit and i would like to use it again. I use VS Code now but I really miss the Nedit macros with keystroke recording.   I have not since found a text editor that has a macro engine as good as Nedit.   Thanks for the great project.  I hope to try it soon.

I use Windows OS these days and I noticed a comment on this thread https://sourceforge.net/p/nedit/discussion/34507/thread/b99a9c0a/#ac55 which stated that Nedit can be compiled on Windows!!   Please could you provide some instructions (or just hints) on the best way of compiling for windows.  I've installed CMake and Qt but i wasn't sure about the version for Bison.   
Thanks.

**Comment by eteran** [comment]
I'll setup something on the Wiki when I get a chance :-). There is still a bit of manual configuration needed to build things, but it's nothing outlandish

**Comment by eteran** [comment]
Took care of the bison dependency. Now it'll use prebuilt files on systems which don't have bison installed.

So the only complication is in helping it find boost. I'll try to come up with some nice instructions for that.

**Comment by DougRzz** [comment]
@eteran i had no plans in particular.  i am happy to use visual studio community edition. Instructions would be great. Will stand alone binaries be generated? if yes, would the license agreement allow me to upload the binaries to a public repo?

**Comment by eteran** [comment]
The binaries will depend on Qt's dll's and the visual studio runtime dlls, I think that is all.

As for the license agreement, I suppose it will be generally fine, though I'd like to have at least **some** input on binaries and their labeling of official vs. non-official builds if they're going to be upload to a third party site. We can discuss those details once you've got a successful build going :-).

**Comment by lester96** [comment]
I have built a working nedit-ng on Windows 10 now, but besides opening the nedit window, it also opens a cmd window.  Closing the cmd window also closes the nedit window. Do you know how to prevent needing the cmd window, or how to have it opened minimized?  I followed your instructions to build nedit, the biggest problem was figuring out which boost to use.

**Comment by eteran** [comment]
It's great that it builds for you! I'll look into why the command window pops up, and see if there's an easy fix

**Comment by eteran** [comment]
Looks like it was as simple as setting a linker variable. Please try the latest and let me know if it no longer has the console window :-).

**Comment by eteran** [comment]
As a side note, for things to function correctly outside of being run in QrCreator, you will need to copy the following dlls from the Qt bin directory (add a to the names for a debug build):

* Qt5Network.dll
* Qt5Xml.dll
* Qt5PrintSupport.dll
* Qt5Widgets.dll
* Qt5Gui.dll
* Qt5Core.dll
* Qt5Svg.dll

**Comment by aks2161989** [comment]
@eteran I tried compiling Nedit-ng on Windows 10 according to the instructions given [here ](https://github.com/eteran/nedit-ng/wiki/Compiling-on-Windows). I ran into the following errors:

`F:\cpp_programming\nedit-ng\GSL\CMakeLists.txt:9: error: INTERFACE_LIBRARY targets may only have whitelisted properties.  The property "EXCLUDE_FROM_ALL" is not allowed.`

The messages generated by QtCreator are:

> Running Windows Runtime device detection.
> No winrtrunner.exe found.
> 2019-02-17T16:19:54 Clang Code Model: Error: The clangbackend executable "G:\Qt\Tools\QtCreator\bin\clangbackend.exe" could not be started (timeout after 10000ms).
> Running "C:\Program Files\CMake\bin\cmake.exe -E server "--pipe=\\.\pipe\{7d1c3fb9-53d4-40f2-835e-a8f869ccb2cb}" --experimental" in C:\Users\USER\AppData\Local\Temp\QtCreator-rupKGg\qtc-cmake-DuWZBUzv.
> QLocalSocket::connectToServer: Invalid name
> QLocalSocket::connectToServer: Invalid name
> QLocalSocket::connectToServer: Invalid name
> Starting to parse CMake project, using: "-D"BOOST_ROOT":PATH=F:\Build_libraries_here\boost_1_69_0", "-DBOOST_ROOT:PATH=F:\Build_libraries_here\boost_1_69_0", "-DCMAKE_CXX_COMPILER:STRING=G:/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/HostX86/x64/cl.exe", "-DCMAKE_C_COMPILER:STRING=G:/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/HostX86/x64/cl.exe", "-DCMAKE_PREFIX_PATH:STRING=G:/Qt/5.12.1/msvc2017_64", "-DQT_QMAKE_EXECUTABLE:STRING=G:/Qt/5.12.1/msvc2017_64/bin/qmake.exe".
> The CXX compiler identification is MSVC 19.16.27024.1
> Check for working CXX compiler: G:/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/HostX86/x64/cl.exe
> Check for working CXX compiler: G:/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/HostX86/x64/cl.exe -- works
> Detecting CXX compiler ABI info
> Detecting CXX compiler ABI info - done
> Detecting CXX compile features
> Detecting CXX compile features - done
> Boost version: 1.69.0
> Found Git: F:/Git/cmd/git.exe (found version "2.15.1.windows.2") 
> CMake Error at GSL/CMakeLists.txt:9 (add_library):
>   INTERFACE_LIBRARY targets may only have whitelisted properties.  The
>   property "EXCLUDE_FROM_ALL" is not allowed.
> 
> 
> Configuring incomplete, errors occurred!
> See also "C:/Users/USER/AppData/Local/Temp/QtCreator-rupKGg/qtc-cmake-DuWZBUzv/CMakeFiles/CMakeOutput.log".
> CMake Project parsing failed.
> 

I am using CMake 3.14.0-rc1.

Can you offer any suggestions?

Thanks

**Comment by eteran** [comment]
Strange, I've never seen that error. The cmake file mentioned is from GSL, so I'll look into if it had an update available. If not, I'll look into a workaround.

**Comment by eteran** [comment]
@aks2161989 I've updated to the latest GSL code. I haven't seen your issue myself, so if you can confirm whether or not it fixes the build for you.

**Comment by aks2161989** [comment]
@eteran I deleted the earlier directory and recloned the nedit-ng repository. I followed all the steps as given in the wiki, but I get the same error:

`F:\cpp_programming\nedit-ng\GSL\CMakeLists.txt:9: error: INTERFACE_LIBRARY targets may only have whitelisted properties.  The property "EXCLUDE_FROM_ALL" is not allowed.`

QtCreator generates the following messages:

> 
> Running Windows Runtime device detection.
> No winrtrunner.exe found.
> 2019-02-18T22:43:57 Clang Code Model: Error: The clangbackend executable "G:\Qt\Tools\QtCreator\bin\clangbackend.exe" could not be started (timeout after 10000ms).
> Running "C:\Program Files\CMake\bin\cmake.exe -E server "--pipe=\\.\pipe\{9e55e335-bcf7-4978-9485-b83139ece447}" --experimental" in C:\Users\USER\AppData\Local\Temp\QtCreator-uODwFi\qtc-cmake-tJJGBARW.
> Starting to parse CMake project, using: "-DCMAKE_CXX_COMPILER:STRING=G:/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/HostX86/x64/cl.exe", "-DCMAKE_C_COMPILER:STRING=G:/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/HostX86/x64/cl.exe", "-DCMAKE_PREFIX_PATH:STRING=G:/Qt/5.12.1/msvc2017_64", "-DQT_QMAKE_EXECUTABLE:STRING=G:/Qt/5.12.1/msvc2017_64/bin/qmake.exe".
> The CXX compiler identification is MSVC 19.16.27024.1
> Check for working CXX compiler: G:/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/HostX86/x64/cl.exe
> Check for working CXX compiler: G:/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/HostX86/x64/cl.exe -- works
> Detecting CXX compiler ABI info
> Detecting CXX compiler ABI info - done
> Detecting CXX compile features
> Detecting CXX compile features - done
> CMake Error at C:/Program Files/CMake/share/cmake-3.14/Modules/FindBoost.cmake:2124 (message):
>   Unable to find the requested Boost libraries.
> 
>   Unable to find the Boost header files.  Please set BOOST_ROOT to the root
>   directory containing Boost or BOOST_INCLUDEDIR to the directory containing
>   Boost's headers.
> Call Stack (most recent call first):
>   CMakeLists.txt:71 (find_package)
> 
> 
> Found Git: F:/Git/cmd/git.exe (found version "2.15.1.windows.2") 
> CMake Error at GSL/CMakeLists.txt:9 (add_library):
>   INTERFACE_LIBRARY targets may only have whitelisted properties.  The
>   property "EXCLUDE_FROM_ALL" is not allowed.
> 
> 
> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
> Please set them or make sure they are set and tested correctly in the CMake files:
> F:/cpp_programming/nedit-ng/Interpreter/Boost_INCLUDE_DIR
>    used as include directory in directory F:/cpp_programming/nedit-ng/Interpreter
> F:/cpp_programming/nedit-ng/Util/Boost_INCLUDE_DIR
>    used as include directory in directory F:/cpp_programming/nedit-ng/Util
> F:/cpp_programming/nedit-ng/client/Boost_INCLUDE_DIR
>    used as include directory in directory F:/cpp_programming/nedit-ng/client
> F:/cpp_programming/nedit-ng/src/Boost_INCLUDE_DIR
>    used as include directory in directory F:/cpp_programming/nedit-ng/src
> 
> Configuring incomplete, errors occurred!
> See also "C:/Users/USER/AppData/Local/Temp/QtCreator-uODwFi/qtc-cmake-tJJGBARW/CMakeFiles/CMakeOutput.log".
> CMake Project parsing failed.
> Starting to parse CMake project, using: "-D"BOOST_ROOT":PATH=F:\Build_libraries_here\boost_1_69_0", "-DCMAKE_CXX_COMPILER:STRING=G:/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/HostX86/x64/cl.exe", "-DCMAKE_C_COMPILER:STRING=G:/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/HostX86/x64/cl.exe", "-DCMAKE_PREFIX_PATH:STRING=G:/Qt/5.12.1/msvc2017_64", "-DQT_QMAKE_EXECUTABLE:STRING=G:/Qt/5.12.1/msvc2017_64/bin/qmake.exe".
> Boost version: 1.69.0
> CMake Error at GSL/CMakeLists.txt:9 (add_library):
>   INTERFACE_LIBRARY targets may only have whitelisted properties.  The
>   property "EXCLUDE_FROM_ALL" is not allowed.
> 
> 
> Configuring incomplete, errors occurred!
> See also "C:/Users/USER/AppData/Local/Temp/QtCreator-uODwFi/qtc-cmake-tJJGBARW/CMakeFiles/CMakeOutput.log".
> CMake Project parsing failed.
> Starting to parse CMake project, using: "-D"BOOST_ROOT":PATH=F:\Build_libraries_here\boost_1_69_0", "-DCMAKE_CXX_COMPILER:STRING=G:/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/HostX86/x64/cl.exe", "-DCMAKE_C_COMPILER:STRING=G:/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/HostX86/x64/cl.exe", "-DCMAKE_PREFIX_PATH:STRING=G:/Qt/5.12.1/msvc2017_64", "-DQT_QMAKE_EXECUTABLE:STRING=G:/Qt/5.12.1/msvc2017_64/bin/qmake.exe".
> Boost version: 1.69.0
> CMake Error at GSL/CMakeLists.txt:9 (add_library):
>   INTERFACE_LIBRARY targets may only have whitelisted properties.  The
>   property "EXCLUDE_FROM_ALL" is not allowed.
> 
> 
> Configuring incomplete, errors occurred!
> See also "C:/Users/USER/AppData/Local/Temp/QtCreator-uODwFi/qtc-cmake-tJJGBARW/CMakeFiles/CMakeOutput.log".
> CMake Project parsing failed.

I don't understand what am I doing wrong?

**Comment by eteran** [comment]
Can you try opening the root `CMakeList.txt` (for you, in `F:\cpp_programming\nedit-ng\`  and changing line 150 to read:

    add_subdirectory(GSL)

instead of

    add_subidrectory(GSL EXCLUDE_FROM_ALL)

and see if that fixes it for you?

**Comment by aks2161989** [comment]
Thank you so much! That solved the problem. I was able to compile and run the editor successfully.

**Comment by aks2161989** [comment]
@eteran The editor runs well, but I have observed a minor inconsistency - When I run the editor by pressing F5 in QtCreator, it shows a little red cross on the right corner of the file tab. But, when I run the editor by navigating to the directory and double-clicking it, I cannot see that red cross.

When running from QtCreator-
![screenshot 13](https://user-images.githubusercontent.com/20129646/53038743-7e03c280-34a3-11e9-947a-548c1280ef43.png)

When running from directory-
![screenshot 14](https://user-images.githubusercontent.com/20129646/53038777-8fe56580-34a3-11e9-8523-a05561f305f1.png)

I have pasted the following Qt dlls in the directory (Did I miss anything?)
![screenshot 15](https://user-images.githubusercontent.com/20129646/53038816-a12e7200-34a3-11e9-8e8f-a78036eaa0ed.png)

**Comment by eteran** [comment]
Yea, so that's a failure of the internal image resources loading. Try copying over `Qt5Svg.dll` I **think** that should ensure that they get loaded correctly :-)

**Comment by aks2161989** [comment]
Thanks! that solved the problem.
Is it normal to see the arrow pointer in the editor? I can't see the normal line cursor (that is common in text editors) even when I click on the text...

**Comment by eteran** [comment]
I think that the cursor currently maintains the original behavior of classic nedit. It is trivially changeable though. That's a separate issue, so I'm going to close this one 🙂
