### ISSUE TITLE
Please provide binaries for Windows 

### ISSUE THREAD

**Issue by aks2161989** [eteran/nedit-ng#88]
At the risk of sounding lazy, it would be great if you could provide pre-built binaries for Windows (that is the standard practice for Windows apps anyway). Currently, if someone wants to use Nedit-ng, they have to download Qtcreator, Boost and other stuff.

**Comment by eteran** [comment]
Sure, I can make that part of the release process :-)

I'm currently transitioning between jobs and don't have my usual development laptop handy and won't have a replacement until Monday.

**Comment by aks2161989** [comment]
Sounds cool!

**Comment by eteran** [comment]
Next release, which I plan on being this month. I will upload binaries for windows :-)

**Comment by greenpad2** [comment]
I eagerly await Windows binaries!  Thanks for doing this.

**Comment by eteran** [comment]
2019.2 Released!

I have uploaded in the release a win32 for x86-64 which uses the msvc-2017 runtime!

Let me knowhow it goes :-)

**Comment by greenpad2** [comment]
This is awesome!  It runs on my system!  I'll still primarily use this on linux but I do sometimes need to edit text files in Windows and it will be great to have uniformity.  Thank you so much!

**Comment by Rimpire** [comment]
I cannot find any binary among 2019.2 tag files. Am i looking at the wrong place ?

**Comment by eteran** [comment]
@Rimpire no, I just haven't gotten around to uploading a windows build. I'll have to add that to be part of my release process. Coming soon!
