### ISSUE TITLE
dialog window

### ISSUE THREAD

**Issue by marilmanen** [eteran/nedit-ng#91]
Minor issues with built-in subroutine dialog() window
1. window is not automatically resized to show all text
2. selecting text from the window is not possible
3. window does not have title, maybe the macro command could be used

Here is the macro I used for testing
dialog(shell_command("git status", ""), "OK")

Additional note: My first macro trial was syntactically incorrect
dialog(shell_command("git status"), "OK")
and it is accepted by the Macro Commands/Check

**Comment by eteran** [comment]
I didn't change the macro engine, so if it accepts the command, I suspect the original nedit did as well.

I'll look into this though.

**Comment by eteran** [comment]
I was able to make the label selectable and at least for now put **something** as the dialog title. Using the macro name is a good idea, but that information isn't quite threaded down to that layer easily, so it's just "Nedit-ng" for now. I'll see if we can do better...

As for the first issue of not automatically resizing, this is a surprisingly hard issue to address! Qt just doesn't want to do it. I'll continue to look into it, but it's proving to a challenge.

**Comment by marilmanen** [comment]
About the resize: Could you just add QWidget::adjustSize() to DialogPrompt::showEvent in DialogPrompt.cpp? It looks like it works, but please note that I just make trials without any knowledge how things should be done.

**Comment by eteran** [comment]
Hmm, I thought I had tried that, but I'll look again.

**Comment by eteran** [comment]
Hmm, looks like that's basically the one thing I didn't try! I'll get an update in there ASAP.

**Comment by eteran** [comment]
Should be fixed!

**Comment by marilmanen** [comment]
Could you fix window resize also for list_dialog. Here is a dummy example macro.
list_dialog("Select", "this should be long enough string for testing list dialog size issue", "OK")

**Comment by eteran** [comment]
@marilmanen 

The contents of the list box causing the dialog box to need a resize is a slightly different more complex issue. I'm going to create a separate issue for it.
