### ISSUE TITLE
Windows binary doesn't work

### ISSUE THREAD

**Issue by xenu** [eteran/nedit-ng#94]
It fails with the following error:

>This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Consider using [windeployqt](https://doc.qt.io/qt-5/windows-deployment.html), it will  take care of dependencies for you.

**Comment by eteran** [comment]
I'll take a look at the tool

**Comment by eteran** [comment]
OK, I updated the release using the windeployqt tool. Hopefully, that should address your problem. Please re-open the issue if the problem persists.

**Comment by xenu** [comment]
Thank you, it works now.

**Comment by eteran** [comment]
Awesome!
