### ISSUE TITLE
crash with replace dialog opened

### ISSUE THREAD

**Issue by patricevenant** [eteran/nedit-ng#95]
Hi,

I got a crash of nc-ng when I play with the following sequence:  
1) on a shell prompt,  $ nc-ng filea fileb filec
2) on filec windows, I open the Replace dialog (Ctrl-R), I select [x] keep Dialog and [x] Case Sensitive
3) choose string to replace, I push "Replace all in: [Window]"
4) I save (Ctrl-S) and close (Ctrl-W)
5) I do the same on fileb (from step 2) - replace string with same Replace Dialog
6) I do the same on filea (from step 2)
Now, I got the Untitled window with the Replace Dialog still opened.
I start again the process from 1) means nc-ng filea fileb filec.
I replace different strings. I loop two/three time from 1) and then nc-ng crash, I lost all windows.

Hope you will be able to reproduce on your side...
Regards,
Patrice

**Comment by patricevenant** [comment]
In fact, I wasn't playing with the latest version of nc-ng. After the git pull, I can't reproduce the crash now. I close the issue.
Patrice

**Comment by eteran** [comment]
Great, my first question was going to be "what version?" 🙂. Thanks for the report anyway, will be helpful for anyone who runs into the same crash
